### ISSUE TITLE
Extract compressor as generic gem

### ISSUE THREAD

**Issue by dhh** [rails/tailwindcss-rails#1]
Tailwind CSS needs purging, but it's a generic technique that could be used with any css toolkit. Should extract this into a generic gem. Maybe `sprockets-css-purger`, then this gem can use that, and focus mostly just on configuration and shipping the tailwind css.

**Comment by dhh** [comment]
This is btw and open invitation to anyone who'd like to work on this 😄

**Comment by dixpac** [comment]
@dhh  I will give it a go, after I finish the scaffolds.
