### ISSUE TITLE
Doesn't work on macOS (M1)

### ISSUE THREAD

**Issue by manastyretskyi** [rails/tailwindcss-rails#101]
Hello,
I have created new rails app with `--css tailwind` flag.
Neither `rails tailwindcss:build` nor `rails tailwindcss:watch` produce any output and fail silently.
TailwindCSS executable doesn't seem to be installed with gem.

In my case command that is executed under the hood looks like this:
`/Users/user/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/tailwindcss-rails-2.0.0/lib/tasks/../../exe/tailwindcss -i /Users/user/project/app/assets/stylesheets/application.tailwind.css -o /Users/user/project/app/assets/builds/tailwind.css -c /Users/user/project/config/tailwind.config.js`

And when I try to execute it manually I get:
`zsh: no such file or directory: /Users/user/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/tailwindcss-rails-2.0.0/lib/tasks/../../exe/tailwindcss`

**Comment by dhh** [comment]
What version of macOS are you? Latest?

**Comment by manastyretskyi** [comment]
Yes, I'm using macOS Monterey 12.1 (21C52).

**Comment by manastyretskyi** [comment]
Also I found other people complain about same issue https://github.com/rails/tailwindcss-rails/pull/96#issuecomment-997236383 but this solution didn't work for me.

**Comment by dixpac** [comment]
`bundle show` should display something like `.../gems/tailwindcss-rails-2.0.0-arm64-darwin`, in your case it has installed gem without the platform..same issue I had but I'm on the BigSur 11.6.

Is that specific project where it doesn't work or it is not working at all?

**Comment by manastyretskyi** [comment]
First I tried to add `tailwindcss-rails` to an existing project, but it didn't work, then I created new project using `rails new test --css tailwind` and it didn't work as well.

**Comment by dixpac** [comment]
When you open irb (for that ruby version 3.0.0 as I can see) and inspect `RUBY_PLATFORM`
```ruby
# irb
RUBY_PLATFORM
```

What value does this constant prints?

**Comment by manastyretskyi** [comment]
```
irb(main):001:0> RUBY_PLATFORM
=> "arm64-darwin21"
```

**Comment by flavorjones** [comment]
I'll try to take a look today.

**Comment by flavorjones** [comment]
See #102 for a potential fix

**Comment by dhh** [comment]
Addressed via https://github.com/rails/tailwindcss-rails/pull/102 👍

**Comment by manastyretskyi** [comment]
After updating to version `2.0.1` I get this message:

```
ERROR: Cannot find the tailwindcss executable for arm64-darwin-21 in /Users/user/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/tailwindcss-rails-2.0.1/exe
If you're using bundler, please make sure you're on the latest bundler version:

  gem install bundler
  bundle update --bundler

Then make sure your lock file includes this platform by running:

  bundle lock --add-platform arm64-darwin-21
  bundle install

See `bundle lock --help` output for details.
```

After I ran suggested commands, `tailwindcss-rails (2.0.1-arm64-darwin)` is added to `Gemfile.lock`, but when I run `rails tailwindcss:build` I get the same message.

**Comment by manastyretskyi** [comment]
Update to my previous comment. After `bundle lock --add-platform arm64-darwin-21` and `bundle install` two gem versions were added to the Gemfile.

```
    tailwindcss-rails (2.0.2)
      railties (>= 6.0.0)
    tailwindcss-rails (2.0.2-arm64-darwin)
      railties (>= 6.0.0)
```

After I removed vanilla ruby version manually everything started to work.
