### ISSUE TITLE
VSCode Tailwind Extension?

### ISSUE THREAD

**Issue by sprite2005** [rails/tailwindcss-rails#109]
Does anyone know how to get this working in Rails 7 with the Tailwind CSS VS Code extension?

[Error - 9:25:27 AM] Tailwind CSS: Can't resolve 'tailwindcss'

**Comment by alex-damian-negru** [comment]
From what I noticed the VSCode extension looks for the `tailwind.config.js` under root namespace, while this gem expects it under `config`. 

Although not a viable solution, it might help if you duplicate the file to have it in both namespaces. I haven't found an option to provide the namespace where either this gem or the VSC extension should look for the file.

**Comment by stephenbiggs** [comment]
I've also been struggling to get this to work. The above suggestion didn't seem to resolve the issue. Look forward to potential solutions.

**Comment by richjdsmith** [comment]
There is a related thread that discusses this issue for other rails users. may also have to do with TailwindCSS 3. 

https://github.com/tailwindlabs/tailwindcss-intellisense/issues/448

**Comment by Admiral-Enigma** [comment]
I get the same error 
`[Error - 19.52.33] Tailwind CSS: Can't resolve 'tailwindcss' in 'c:\Users\User\Desktop\railsproject\config'`
So it's looking in the right folder but I think it may be related to the fact that the `tailwindcss` node package is missing as a dev dependency.

**Comment by onurozer** [comment]
I have the same error. It looks like Tailwind Extension does not work with the CLI version of Tailwind.

**Comment by bpo** [comment]
[Release v0.7.5](https://github.com/tailwindlabs/tailwindcss-intellisense/releases/tag/v0.7.5), from 2 days ago, [ships with its own copy of the node package](https://github.com/tailwindlabs/tailwindcss-intellisense/issues/455) - that resolves this issue for me.
