### ISSUE TITLE
What is the recommended way to use a different font?

### ISSUE THREAD

**Issue by odinsride** [rails/tailwindcss-rails#113]
Coming from the webpacker/yarn method of adding @fontsource packages for fonts, that doesn't seem to work with this gem. For now, I've resorted to linking to the font externally from Google Fonts.  Do I simply need to download the font into assets (and configure CSS accordingly) if I want to self-host it?

**Comment by dixpac** [comment]
@odinsride exactly. You should download fonts and place them inside the `app/assets/fonts/` and hook the font with the tailwind css something like [this](https://www.youtube.com/watch?v=sOnBG2wUm1s)

Hope this helps 😄

**Comment by odinsride** [comment]
Thanks for clearing that up!
