### ISSUE TITLE
Dev Server/Tailwind Watch Mode Not Refreshing

### ISSUE THREAD

**Issue by richjdsmith** [rails/tailwindcss-rails#119]
I can't replicate this so I'm going to create this issue then close it in hopes it helps some other poor bugger googling the issue. When I was running my rails server (locally only) and running Tailwind in watch mode, I had a funny issue where Tailwind was producing a new version of `application.css` but my rails server was not using the new version.

If I restarted the rails server, it had no effect. If I ran `rails assets:precompile', it would produce a new version of the tree-shaken `applicaiton.css` but the dev server would not use it. I could not use new tailwind classes in my code. 

The solution: `rails assets:clobber`

That sorted it out and got my server acting as expected. I have no idea why. This was running on a project that was a couple hours hold running Rails 7.0, Ruby 3.0.3 and using the tailwindcss-rails gem for Tailwind. 

I have tried to replicate this but have not been able to. Hoping at least this will help someone else from a couple of hours tearing out their hair.

**Comment by viktorshamal** [comment]
Thank you for saving me from tearing out my hair ❤️

**Comment by multiplegeorges** [comment]
@richjdsmith Saved me too, thanks!

**Comment by dhh** [comment]
Sounds like you had precompiled locally. Precompiled files take precedence over dynamic files with Sprockets.

**Comment by fabioacd** [comment]
Thank you!! I was going crazy with this error.

`rails tailwindcss:watch` was working just fine and it went down when I installed the gem 'rails_live_reload'. In my case that could be the cause of the error.

Thanks again

**Comment by alanenglish** [comment]
I am not sure what I am missing here.. Just created a new rails 7 app via `rails new test-app -T -d postgresql -c tailwind`, and whether I run `rails s` and `rails tailwindcss:watch` both, or just `bin/dev`, none of the CSS classes I add in `.erb` files cause a refresh, I always have to manually refresh the browser to have the new styles appear..

Running `rails assets:clobber` doesn't seem to do anything for me..

I feel like I have to be doing something wrong, but haven't changed a single thing as far as configuration goes.. Literally just created the app and went to test this out.

**Comment by fh0enix** [comment]
Thank you! That is very helpful.

**Comment by khanhdang2911** [comment]
Thank you, I followed your instructions and it worked.
