### ISSUE TITLE
@layer directive does not seem to be working in default rails 7 integration. How to add custom base styles?

### ISSUE THREAD

**Issue by someka** [rails/tailwindcss-rails#126]
After generating a brand new Rails 7 project with Tailwindcss:

`rails new project --css tailwind`

application.tailwind.css has been created automatically. Nice. But @layer directive written here does not have any effect:

```
@layer base {
  h1 {
    @apply text-2xl;
  }
  h2 {
    @apply text-xl;
  }
}
```

Coming from this link: https://tailwindcss.com/docs/adding-base-styles

Am I missing something? Or what is the best way to add custom base styles?

_OS: Windows 10
Environment: Development_

**Comment by davidteren** [comment]
@someka if like myself you ran `tailwindcss init` which adds the `tailwindcss.config.js` to the app root and found the custom themes are not working it's because the install copies it to `config/tailwindcss.config.js` 

```ruby
unless Rails.root.join("config/tailwind.config.js").exist?
  say "Add default config/tailwindcss.config.js"
  copy_file "#{__dir__}/tailwind.config.js", "config/tailwind.config.js"
end
```

see here: [tailwindcss.config.js](https://github.com/rails/tailwindcss-rails/blob/651d5a7dd50c697d1933e7386711db9c8f38f038/lib/install/tailwindcss.rb#L29)

**Comment by dixpac** [comment]
@someka 👋🏼  ,  I've just tested the same thing and it works fine on my mac(altho I can't see that this could be OS released issue).
Do you have demo app that reproduces the issue, so I can double check?
(Here is mine that works https://github.com/dixpac/project)

**Comment by someka** [comment]
> @someka if like myself you ran `tailwindcss init` which adds the `tailwindcss.config.js` to the app root and found the custom themes are not working it's because the install process copies it to `config/tailwindcss.config.js`
> 
> ```ruby
> unless Rails.root.join("config/tailwind.config.js").exist?
>   say "Add default config/tailwindcss.config.js"
>   copy_file "#{__dir__}/tailwind.config.js", "config/tailwind.config.js"
> end
> ```
> 
> see here: [tailwindcss.config.js](https://github.com/rails/tailwindcss-rails/blob/651d5a7dd50c697d1933e7386711db9c8f38f038/lib/install/tailwindcss.rb#L29)
> 
> Perhaps this is your issue?

@davidteren Sorry for the late reply. As I've mentioned I have ran the default command to install a new app including tailwind framework (which is an option now in rails 7). That can be OS related as @dixpac mentioned. However, I gave up and switched back to using Bootstrap. (will definitely come back in the future though to try again)
