### ISSUE TITLE
How to specify image or asset url in CSS

### ISSUE THREAD

**Issue by frogandcode** [rails/tailwindcss-rails#129]
How does one specify the url of a background image (or other asset in the asset pipeline) in `application.tailwind.css` so that the asset url is generated properly?

With the `sass-rails` gem, I believe the following approaches work:

```
background-image: image-url(‘waves.png’);
// or
background-image: url(image_path(‘waves.png’));
```

I’ve tried both of these (along with `asset_path`) with tailwind-rails to no avail.

Has anyone done this in their application? Thanks!

**Comment by dhh** [comment]
`url('waves.png')` will be rewritten to use asset pipeline with latest sprockets-rails automatically 👍

**Comment by connordoner** [comment]
Just in case anyone ever comes back to this, make sure to restart your development server with `./bin/dev`.
