### ISSUE TITLE
Multiple CSS files for Tailwind apply directives

### ISSUE THREAD

**Issue by mathias234** [rails/tailwindcss-rails#133]
Hey!

We have used tailwind for some time in our project and are now attempting to upgrade to Rails 7 with importmaps and this gem instead of Node. 
We seem to have stumbled upon a problem with how we arranged our CSS files as we had split them over multiple files and done @import in our application.css file. If we do that with this gem we just get these errors
![screenshot](https://user-images.githubusercontent.com/2104029/148767419-6b5ce323-8076-42c4-822c-5b4bccfdbeac.png)

The CSS will start working again if we merge all into the application.tailwind.css but that results in a large and unwieldy file. So the main question is: Is there a way to have multiple CSS files that are compiled by tailwind without using Node

**Comment by dixpac** [comment]
From my research on this, at the moment there is not, since there is no postcss plugin.
Also I'm not sure if this is tailwindcss-rails or tailwind standalone cli build issue.

But, I may be wrong on this one, i didn't spend a lot of time researching this issue.

**Comment by mathias234** [comment]
> From my research on this, at the moment there is not, since there is no postcss plugin. Also I'm not sure if this is tailwindcss-rails or tailwind standalone cli build issue.
> 
> But, I may be wrong on this one, i didn't spend a lot of time researching this issue.

I don't think it's really an issue/bug from either this gem or the CLI tool, it's just not a feature. Tailwind CLI only seem to accept one file to it and does not have functionality to include other files, as far as I understand

**Comment by dhh** [comment]
If you're using HTTP2, no substantial benefit for bundling CSS into a single file. You can refer to multiple files just fine. Either way, it's indeed not a feature of this standalone TW setup.

**Comment by mathias234** [comment]
@dhh The point was not to have bundling, but my understanding is tailwind needs to "build" each CSS file and there seem to be no way to make this happen. So if I just link to the CSS file the `@apply` directives will not be resolved and i get the errors you see in the screenshots

**Comment by dhh** [comment]
I don't think I follow? Is it that you're using `@apply` in multiple files? If so, I'd just stop doing that 😄. As I understand it, @apply is meant to be a sparse, rare usage. If you're doing it so much you need multiple files to contain it all, I think it's worth considering if Tailwind is the right fit.

**Comment by dixpac** [comment]
> I don't think it's really an issue/bug from either this gem or the CLI tool, it's just not a feature. Tailwind CLI only seem to accept one file to it and does not have functionality to include other files, as far as I understand

👍🏼 

@dhh issue here is that it is "common" practicle to separate components into different files
```
styleshhets/
  components/
   button.css
   card.css
 application.css
```
And then include those components using `@import` inside the `application.css`

But, with standalone CLI that is not possible since there is no postcss

**Comment by dhh** [comment]
I think such a setup sorta defeats the purpose of Tailwind, to be honest. Their tag line is literally "Rapidly build modern websites without ever leaving your HTML". Anyway, it is what it is, if you're using the standalone version of Tailwind. If you must have postcss, then you'll need the whole Node enchilada.

**Comment by mathias234** [comment]
I agree that we may be overusing the `@apply` after from reading closer in tailwind's docs it's definitely not the recommended way

**Comment by dixpac** [comment]
We made the same "mistake" in the past @mathias234 , it takes a time to adjust after BEM or similar stuff 😅

**Comment by DanielJackson-Oslo** [comment]
+1 to this. I would love to be able to keep my railsy CSS structure with several small CSS files in stylesheets, while still being able to sprinkle a little heretical `@apply` in them when needed. 

I guess just a tiny ruby pre-compiler that watches and simply merges all css files in /stylesheets/ before handing them over to tailwind would do the trick without node and in very few lines of code? @mathias234 wrote a hack to that effect here: https://github.com/lnu-norge/lokaler.lnu.no/blob/c13668de1aaa723a1432b87db46a0b12d146c96b/lib/tasks/css_packer.rake

> I think such a setup sorta defeats the purpose of Tailwind, to be honest. Their tag line is literally "Rapidly build modern websites without ever leaving your HTML". Anyway, it is what it is, if you're using the standalone version of Tailwind. If you must have postcss, then you'll need the whole Node enchilada.

To me Tailwind has become both a way to rapidly build without leaving my HTML, but also a design system that adds consistency.  When Tailwind can't keep up with all my CSS needs, I end up using a few CSS files as well - usually split into several small files to try to keep them from getting too messy - and then I use `@apply` to get that sweet consistency of colours, margins, and more. 

Typical use cases where I feel tailwind-in-html falls short and I find myself reaching for `@apply`:

1. Styling third party HTML with set classes (impossible with tailwind)
2. Styling standard content typography (p, a, h1, etc. (feels impractical to make custom view_components or whatever for all of them)
3. "Combined utility classes" for combinations of utility classes I repeat on several different components and would want to change one place to change them all

Genuinely looking to learn here: Is using `@apply` wrong for these cases? It feels natural to keep tailwind-in-html as far as it can take me, but then eject to CSS for these cases - and I don't think we have over-done it? 

For number 1 I don't see any other way to do it - but I guess the other two could be mostly achieved by creating composable components, but I guess that would require view_components too? Or could I do it efficiently and nicely with vanilla rails?

**Comment by dhh** [comment]
I'm not so much rendering an opinion on right or wrong, as much as just parroting what the TW guidelines are. As well as of course just noting the inherent constraints we have using the standalone TW compiler. Ultimately, you should write CSS the way that feels right for your app! And that may well be "I need Node, because I want PostCSS and other stuff" ✌️

**Comment by DanielJackson-Oslo** [comment]
Thanks for the response!

> "I need Node, because I want PostCSS and other stuff" 

Would you be open to a PR that allows for a tiny precompile step that simply combines all css files in /stylesheets/ into one file, that is then passed to tailwind? Written with pure ruby code and without ever needing Node, of course. 

Not unlike what @mathias234 hacked together here: https://github.com/lnu-norge/lokaler.lnu.no/blob/c13668de1aaa723a1432b87db46a0b12d146c96b/lib/tasks/css_packer.rake

**Comment by dhh** [comment]
I think having a small precompiler live in a gem which we can point to from the README makes sense to me 👍

**Comment by AhmedNadar** [comment]
I was able to find away or a solution. 
Within `application.tailwind.css` I wrapped my custom classes which includes `@apply` with`@layer components {}`.
Example...
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer components {
    .auth {
        @apply relative;
        --tw-bg-opacity: 1;
        background-color: rgba(255, 255, 255, var(--tw-bg-opacity));
    }
    .auth:before {
        content: "";
        margin-left: -48%;
        background-image: url("assets/bg-login.svg");
        background-repeat: no-repeat;
        background-size: auto 100%;
        background-position: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
    }
    .auth_container {
        @apply container mx-auto;
    }
    .auth_grid {
        @apply block grid-cols-2 gap-4;
    }
}
```
It works for me and hope it helps.

**Comment by loqimean** [comment]
> Hey!
> 
> We have used tailwind for some time in our project and are now attempting to upgrade to Rails 7 with importmaps and this gem instead of Node. We seem to have stumbled upon a problem with how we arranged our CSS files as we had split them over multiple files and done @import in our application.css file. If we do that with this gem we just get these errors ![screenshot](https://user-images.githubusercontent.com/2104029/148767419-6b5ce323-8076-42c4-822c-5b4bccfdbeac.png)
> 
> The CSS will start working again if we merge all into the application.tailwind.css but that results in a large and unwieldy file. So the main question is: Is there a way to have multiple CSS files that are compiled by tailwind without using Node

Hey man, I have this one solution for me, just create rake task `lib/tasks/csspacker.rake` with the next code:
```# frozen_string_literal: true

desc "Packs all CSS files from app/assets/tailwind_stylesheets into app/assets/application.tailwind.css
      then runs the tailwind build"
task pack_css: :environment do
  files = Dir["./app/assets/tailwind_stylesheets/**/*.css"]

  File.open("./app/assets/stylesheets/application.tailwind.css", "w") do |main_file|
    main_file.write("/* GENERATED FILE! */\n")
    main_file.write("@tailwind base;\n")
    main_file.write("@tailwind components;\n")
    main_file.write("@tailwind utilities;\n")
    main_file.write("\n")

    files.each do |file_path|
      File.open(file_path, "r") do |file|
        loop do
          main_file.write(file.readline)
        rescue StandardError
          main_file.write("\n")
          break
        end
      end
    end
  end
end

Rake::Task['tailwindcss:build'].enhance [:pack_css]

desc "Run tailwind:build on changes in directory app/assets/tailwind_stylesheets"

task 'pack_css:watch' do
  listen = Listen.to(Rails.root.join('app', 'assets', 'tailwind_stylesheets')) do
    Rake::Task[:pack_css].execute
    Rake::Task['tailwindcss:build'].execute
  end

  listen.start
end

Rake::Task['tailwindcss:watch'].enhance ['pack_css:watch']```

@dhh hi, what you can say about this solution?

**Comment by loqimean** [comment]
> @loqimean thanks for providing an alternative.
> 
> A couple things that I've noticed:
> 
> * it requires `gem "listen", "~> 3.8"` in order to work
> * it will replace the original `application.tailwind.css` causing it to become the same as if there were no separate files and duplicating code as you commit it.
> 
> Keep rocking!

So, what about now, TailwindCSS allows to do it in its new version without any additional things

**Comment by fagiani** [comment]
> So, what about now, TailwindCSS allows to do it in its new version without any additional things

Would you mind sharing a bit more about that? I'd really appreciate as I've just created a new rails project and was unable to figure that out.

Thanks a bunch!

**Comment by fagiani** [comment]
@loqimean thanks for pointing that out.

I've checked I had latest tailwind version and tried that approach both with `@import` and `@tailwind` and none worked... it will actually import those into `application.css` with all `@apply` within it thus not parsing at all.

Please let me know if you have had any further progress with it.

I really appreciate your help here.

**Comment by brunoprietog** [comment]
With the latest version of the gem, I have something like this and it works

In app/assets/stylesheets/application.tailwind.css:

```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
@import "./buttons.css";

/* You can put css here too */
```

Then in app/assets/stylesheets/buttons.css:

```css
@layer components {
  .btn {
    @apply px-6 py-4;
    @apply rounded-lg shadow-xl;
    @apply hover:cursor-pointer;
  }
}
```

**Comment by fagiani** [comment]
> With the latest version of the gem, I have something like this and it works

@brunoprietog Thanks a lot for taking the time to help along.

I've created a brand new project with the same code you pasted above and it is [publicly available here](https://github.com/fagiani/rails-tailwind-sample/tree/main)

Somehow it will get a bit messed up as it will get both versions conflicting.

There is a `/posts` scaffold just to test the CSS but when trying to inspect this is what i get:

![Screenshot 2023-03-27 at 5 32 47 PM](https://user-images.githubusercontent.com/2450/228059836-f326cb30-d53f-4fe6-82c5-9d1e16e0ba31.png)

![Screenshot 2023-03-27 at 6 01 44 PM](https://user-images.githubusercontent.com/2450/228066447-a9d23ece-cd43-4dce-bacf-10237259c81f.png)

![Screenshot 2023-03-27 at 5 44 30 PM](https://user-images.githubusercontent.com/2450/228062351-6cfa7008-d366-4e2a-b489-810f8103f3d6.png)

![Screenshot 2023-03-27 at 5 46 05 PM](https://user-images.githubusercontent.com/2450/228062571-b1d1b24d-fa1f-4fa2-932d-da57e6c715af.png)

BTW, I've also tried with the defaults with no luck as well:
```ruby
@tailwind base;
@tailwind components;
@tailwind utilities;
@import "./buttons.css"
```

I must be missing some obvious detail here.

I'd sincerely appreciate any insights!

**Comment by brunoprietog** [comment]
Tailwind requires a watcher that rebuilds the CSS when files change. So, you have to run `bin/rails s` in one terminal and `bin/rails tailwindcss:watch` in another. The generator includes a `bin/dev` file, which Foreman uses to run multiple processes in a single terminal window. These processes are defined in the procfile.dev file. So, you have 2 options: Run the commands separately, or run `bin/dev`.

Also, if you are going to follow this approach, I recommend you to use Propshaft instead of Sprockets, you can do it by passing the -a propshaft option to the rails new generator, like this: `rails new myapp --css tailwind -a propshaft`.

Let me know if it works

**Comment by fagiani** [comment]
@brunoprietog I was already using `bin/dev`. Replacing Sprockets with Propshaft did the trick.

Thanks again!

**Comment by iHiD** [comment]
For anyone else finding this, in my (pretty clean) Rails app the `@tailwind` directive stops other imports for working.

ie, this doesn't work:
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@import "./buttons.css";
```

But this does work:
```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@import "./buttons.css";
```

**Comment by Mth0158** [comment]
> For anyone else finding this, in my (pretty clean) Rails app the `@tailwind` directive stops other imports for working.
> 
> ie, this doesn't work:
> 
> ```
> @tailwind base;
> @tailwind components;
> @tailwind utilities;
> 
> @import "./buttons.css";
> ```
> 
> But this does work:
> 
> ```
> @import "tailwindcss/base";
> @import "tailwindcss/components";
> @import "tailwindcss/utilities";
> 
> @import "./buttons.css";
> ```

I had the same issue (Rails 7.1, esbuild, tailwindcss), this worked for me!
