### ISSUE TITLE
Pass argument to tailwind cli

### ISSUE THREAD

**Issue by muriloime** [rails/tailwindcss-rails#136]
Hi all, how can one pass arguments to tailind css CLI. I was expecting something like 

` rails tailwindcss:build --minify` 

to minify css ( by reducing class names, in production), but this doesn't work. Is it possible to do such thing? If not, can you point into the right direction so I can help with the project ? 

[edited to correct command line] 

Many thanks 
Murilo

**Comment by dixpac** [comment]
Rake task that builds the tailwind would need to be enhanced to receive options such as `--minify`. But, I'm not sure if that is really necessary since TW already is small with the JIT.
How much is to gain with the minification?

**Comment by muriloime** [comment]
Hi @dixpac , 

In my application I ran 

`tailwindcss -i app/assets/stylesheets/application.tailwind.css -c config/tailwind.config.js -o teste.css`
`tailwindcss -i app/assets/stylesheets/application.tailwind.css -c config/tailwind.config.js -m -o teste2.css` 

Which generated files of sizes 66.4kb and 46.9kb ( i.e.  40% of reduction). 

But I think there are are other gains if we are able to pass arguments to tailwindcss from `rails tailwindcss:build`, such as allowing more flexibility through use of this gem. 

Many thanks
Murilo

**Comment by dixpac** [comment]
@dhh fixed this via [c76f5d2](https://github.com/rails/tailwindcss-rails/commit/c76f5d22f9344d1ffe205352f189b75d3871d78e)
