### ISSUE TITLE
Don't add main element to application.html.erb

### ISSUE THREAD

**Issue by shafy** [rails/tailwindcss-rails#139]
When installing Tailwind it adds a `main` element like this `<main class="container mx-auto mt-28 px-5 flex">` to `application.html.erb`. While this might be fine with a newly created apps, it's annoying for existing apps since it messes with your existing layout.

I'd either remove this completely or only add it if the `<body>` of `application.html.erb` looks like a default Rails app.

I'm happy to look into this.

**Comment by dixpac** [comment]
@shafy sure give it a try 👍🏼 . `<main>` is added in order to centralize the content, if you are able to accomplish the same without it 👍🏼

**Comment by shafy** [comment]
I see. My point that if you add this gem to an existing project, you probalby already have your HTML set up and wouldn't expect the installer to mess with it. Or am I missing something?

**Comment by shafy** [comment]
Ok thanks for clarifying @dixpac  - I'll have a look and report back :-)
