### ISSUE TITLE
PostCSS support

### ISSUE THREAD

**Issue by svenfinger** [rails/tailwindcss-rails#141]
I’m trying out this Gem as a replacement for [CSS Bundling](https://github.com/rails/cssbundling-rails/) where I use a custom build process via `package.json` (`tailwindcss --postcss --cssnano -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css`) that runs via `bin/dev`.

However, I need to use features such as nesting and import and for that I [must use PostCSS](https://tailwindcss.com/docs/using-with-preprocessors#nesting).

Similar to #138 this would require the task to have more options such as `--postcss`. Am I missing something or is this currently not possible (or not intended?) to be configured in that way?

**Comment by dixpac** [comment]
Not possible nor intended.
Afaik `postcss` requires node, so if you are going with that route then you might be better with using  esbuild or webpack.

**Comment by svenfinger** [comment]
Thanks for clarifying!
