### ISSUE TITLE
Can i use this gem just for the generators for auto styling?

### ISSUE THREAD

**Issue by AhmedKamal20** [rails/tailwindcss-rails#144]
I was watching people using `-c tailwind` when starting new rails app and get auto styling when generating code 
but the thing is, I also create apps using `-c tailwind`, but didn't get the same behavior, nor did I get this gem in my Gemfile
and I discovered that it was like this because I also add `-j esbuild`, and in this case, rails use the npm tailwind, not this gem

My question is, can I add this gem and run the install script to get the auto styling for the `application.html.erb` and the new view I generate without messing up the assets and the tailwind config?

**Comment by dixpac** [comment]
Yes. But you will need to use this gem for the tailwind which means that you will need to use sprockets/propshaft for tailwind instead of esbuild
