### ISSUE TITLE
Multiple CSS files feature

### ISSUE THREAD

**Issue by loqimean** [rails/tailwindcss-rails#145]
Instead of installing postcss_import and other node_modules we can just add something like it, I add this gem, for solving the problem of one file, when people need more than one file:

```
# frozen_string_literal: true

desc "Packs all CSS files from app/assets/tailwind_stylesheets into app/assets/application.tailwind.css
      then runs the tailwind build"
task pack_css: :environment do
  files = Dir["./app/assets/tailwind_stylesheets/**/*.css"]

  File.open("./app/assets/stylesheets/application.tailwind.css", "w") do |main_file|
    main_file.write("/* GENERATED FILE! */\n")
    main_file.write("@tailwind base;\n")
    main_file.write("@tailwind components;\n")
    main_file.write("@tailwind utilities;\n")
    main_file.write("\n")

    files.each do |file_path|
      File.open(file_path, "r") do |file|
        loop do
          main_file.write(file.readline)
        rescue StandardError
          main_file.write("\n")
          break
        end
      end
    end
  end
end

Rake::Task['tailwindcss:build'].enhance [:pack_css]

desc "Run tailwind:build on changes in directory app/assets/tailwind_stylesheets"

task 'pack_css:watch' do
  listen = Listen.to(Rails.root.join('app', 'assets', 'tailwind_stylesheets')) do
    Rake::Task[:pack_css].execute
    Rake::Task['tailwindcss:build'].execute
  end

  listen.start
end

Rake::Task['tailwindcss:watch'].enhance ['pack_css:watch']
```
Then just create your 'tailwind components' in a directory app/assets/tailwind_stylesheets

@dhh hi, what you can say about this solution?

**Comment by Ancez** [comment]
I really like this feature request, and support it. I'm not too sure how much flexibility this will give to the developers though.

I've setup [this template project](https://github.com/Ancez/rails-postcss-tailwind-templates) as that's my preferred setup. This requires PostCSS, whereas this gem doesn't, not sure which solution would be better 🤔

**Comment by loqimean** [comment]
It's possible now by the [TailwindCSS v3.1.8](https://tailwindcss.com/blog/tailwindcss-v3-1#built-in-support-for-css-imports-in-the-cli)
