### ISSUE TITLE
Code Completion for Tailwind classes in RubyMine and other JB IDEs

### ISSUE THREAD

**Issue by Wolwer1nE** [rails/tailwindcss-rails#152]
After legacy file was [removed](https://github.com/rails/tailwindcss-rails/pull/148), no more code completion is available in JB IDEs.
This [plugin ](https://plugins.jetbrains.com/plugin/15321-tailwind-css) is not working (no npm -> no language server, that is reasonable), but previously IDE was able to detect class names from tailwind.css.

Maybe I am missing something, are there any way to use tailwind-rails and get code completion for class names without npm?

**Comment by dhh** [comment]
You can probably just download the full CSS file from TW and point the autocompleter at that?

**Comment by Wolwer1nE** [comment]
@dhh Thank you, that is what I finally settled to. But I had to use full CSS version 2.2.19 because I can't find nothing newer: seems like https://cdn.tailwindcss.com provides script, not CSS directly. Scrolling through files of TW repo and npm installation folder also gave nothing. Probably, at this point it will be better to close this discussion and go to TW repo and ask for full file.

**Comment by gobijan** [comment]
This is not Rails, fault and is purely Jetbrains specific. Works for me in SublimeText or VSCode without problems with the bundled tailwind.

Temporary workaround:
1. Install nodejs
2. npm install tailwindcss postcss autoprefixer (in your project root folder)

Now Rubymine offers completions and also respects the config/tailwind.config.js file.

**Comment by am1006** [comment]
> This is not Rails, fault and is purely Jetbrains specific. Works for me in SublimeText or VSCode without problems with the bundled tailwind.
> 
> Temporary workaround:
> 
> 1. Install nodejs
> 2. npm install tailwindcss postcss autoprefixer (in your project root folder)
> 3. (optional): Add /node_modules, /package-lock.json and /package.json to your .gitignore
> 
> Now Rubymine offers completions and also respects the config/tailwind.config.js file.

This is a life saver! It works perfectly!
