### ISSUE TITLE
Faker gem + view helper + arbitrary color (bg-[#xx]) CSS doesn't render

### ISSUE THREAD

**Issue by ryanckulp** [rails/tailwindcss-rails#157]
hi team,

i'm randomly generating color-coded div elements in my view, here's the idea:
```rb
DashboardHelper
  def random_color
    "bg-[#{Faker::Color.unique.hex_color}]"
  end
end
```

```erb
<div class="<%= random_color %>]">
  ...
</div>
```

the resulting markup is correct, per [Tailwind docs](https://tailwindcss.com/docs/customizing-colors#arbitrary-values):
```erb
<div class="bg-[#1da1f2]">
```

however, **no colors render**. if i remove the `random_color` invocation and simply hard-code a class of `bg-[#1da1f2]`, it works great. please advise.

**Comment by dixpac** [comment]
Hey @ryanckulp 

This is know issue with tailwind and dynamic classes.
👀 this for more infor:
https://github.com/rails/tailwindcss-rails/issues/87
https://tailwindcss.com/docs/content-configuration#dynamic-class-names
