### ISSUE TITLE
Support for MinGW-w64

### ISSUE THREAD

**Issue by engelcalderon** [rails/tailwindcss-rails#162]
I'm working on Windows and my current platform is x64-mingw-ucrt and it throws me this error **tailwindcss-rails does not support the x64-mingw platform**

Is there a plan to support this platform if not yet how can we make it work at the moment on Windows?

**Comment by flavorjones** [comment]
@engelcalderon Unfortunately we're limited right now to the versions of precompiled tailwindcss provided by the upstream maintainers. See https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.0.23 for the latest set (which includes 64-bit windows).

**Comment by flavorjones** [comment]
Ah, sorry, I didn't fully read your original post. The platform `x64-mingw32` is supported. Please check out the README for some helpful hints on what might be going wrong. If you still have a problem, please provide a bit more information about your system and your Gemfile.lock.

**Comment by engelcalderon** [comment]
@flavorjones Thank you for unfortunately is not working, I saw that yeah `x64-mingw32` is working but the only option I see available is `x64-mingw` without the 32. I'm using the latest version of [rubyinstaller]( https://rubyinstaller.org/downloads/ ) do you know by any chance if this is supported?

**Comment by flavorjones** [comment]
@engelcalderon I'll try to clarify. 64-bit windows is supported. If you need assistance getting this working, please provide the information requested above! Thanks!

**Comment by engelcalderon** [comment]
I found the solution, and it was installing [RubyInstaller-3.0.3-1 - 2021-11-27](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.0.3-1)

The issue is that in [RubyInstaller-3.1.0-1 - 2021-12-31](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.1.0-1)  they made the platform to be ` x64-mingw-ucrt` instead of `x64-mingw32` which is not supported yet for tailwindcss-rails.

So far it's working for me, so until we get news I guess this is a solution. Thanks @flavorjones for the help
