### ISSUE TITLE
Overriding scaffold erb templates

### ISSUE THREAD

**Issue by craic** [rails/tailwindcss-rails#164]
Rails 7.0.2.3 ruby 3.0.0p0 ubuntu

I want to modify the erb templates used in scaffolding but the tailwindcss template engine doesn't pick up custom templates from lib/templates/erb/scaffold

Does it use a different location ? I don't see an option in 'rails g scaffold --help' where I can specify that explicitly

Thanks !

**Comment by dhh** [comment]
You can configure which files are watched in tailwind.config.js.

**Comment by mabras** [comment]
> You can configure which files are watched in tailwind.config.js.

Please, can you double-check your answer? It sounds to me like it has nothing to do with the issue.

We are trying to override the erb templates generated by `rails g scaffold [resource]`.
Usually, we put the erb files in locations like:
```
lib/templates/erb/scaffold/*.html.erb
```
Also, I have tried this path:
```
lib/generators/tailwindcss/scaffold/templates/*.html.erb
```
Both are not working.

Thanks @dhh

**Comment by dhh** [comment]
Ah I read it as a watching question. This gem is already overriding the scaffold templates, so that's probably why. Would be happy to look at a PR if you find a way to make this compatible with overwritten templates.

**Comment by craic** [comment]
This source_root line here is overriding the default behaviour

https://github.com/rails/tailwindcss-rails/blob/47f636b12880dc07c9c6210a7c71658186844c5f/lib/generators/tailwindcss/scaffold/scaffold_generator.rb#L1-L9

If I comment that out then I can pick up from 
`lib/templates/erb/scaffold/*.html.erb`

Maybe an if / else clause that looks to see if the app has defined custom templates then use those, if not then use the ones in tailwindcss

Unfortunately I don't see how where the custom template path is defined in the regular generator.
If you can give me a pointer then I will try it out

**Comment by luiskhernandez** [comment]
@craic Not sure if this could be merged into the gem, but overriding the class method `source_root` did the trick.

I added this file `lib/generators/tailwindcss/scaffold/scaffold_generator.rb`

```
require 'rails/generators/erb/scaffold/scaffold_generator'
require "rails/generators/resource_helpers"

module Tailwindcss
  module Generators
    class ScaffoldGenerator < Erb::Generators::ScaffoldGenerator

      def self.source_root
        default_path = Rails.root.join("lib", "templates", "erb", "scaffold")
        return default_path if Dir.exists?(default_path)
        temp = File.expand_path("../templates", __FILE__)
      end
    end
  end
end
```
