### ISSUE TITLE
ActionView::Template errors and precompile errors in Circle CI

### ISSUE THREAD

**Issue by scarrick68** [rails/tailwindcss-rails#171]
Here is the error message when I run tailwind build before specs. I know the docs say it doesn't work with the sassc-rails gem. I have sass-rails which has sassc-rails as a dependency.  The part that's giving me trouble is that tailwindcss:build, assets:precompile, /bin/dev, all work locally even with sass-rails installed. Does sass-rails also need to be removed from the Gemfile and does anyone know why my local set isn't having the SassC::SyntaxError problems?

If I remove sass-rails, I get a bootsnap load error that I haven't been able to resolve yet. I tried purging the load cache. It didn't work.

```
ActionView::Template::Error:
       Error: Function hsla is missing argument $saturation.
               on line 1 of stdin
       >> color}:root,[data-theme]{background-color:hsla(var(--b1)/var(--tw-bg-opaci
          ------------------------------------------^
     # stdin:1
     # ./app/views/layouts/application.html.erb:16:in `_app_views_layouts_application_html_erb___3961564301017774669_33980'
     # ./spec/features/signup_spec.rb:8:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # SassC::SyntaxError:
     #   Error: Function hsla is missing argument $saturation.
     #           on line 1 of stdin
     #   >> color}:root,[data-theme]{background-color:hsla(var(--b1)/var(--tw-bg-opaci
```

**Comment by carlosmedrano97** [comment]
@scarrick68 Were you able to fix it? I'm having the same issue
