### ISSUE TITLE
tailwindcss-rails does not support the x64-mingw platform

### ISSUE THREAD

**Issue by devcamke** [rails/tailwindcss-rails#172]
I am receiving the following error while trying to install tailwindcss on my Windows 10 Systesm.
ruby --version is   3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
rails --version is  7.0.3

**Comment by flavorjones** [comment]
Hi @devcamke, thanks for opening this issue, and sorry you're having this problem.

We ship a native gem that supports x64-mingw, so I'd like to ask for additional information from you to help diagnose what's going on.

Can you please reply with:

* the output from `gem install -V tailwindcss-rails`
* the output from `gem env`
* the output from `bundle env`

Thank you!

**Comment by devcamke** [comment]
The output from gem install -V tailwindcss-rails

PS C:\dev\kamau\bin> gem install -V tailwindcss-rails
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/tailwindcss-rails
200 OK
GET https://index.rubygems.org/quick/Marshal.4.8/tailwindcss-rails-2.0.8.gemspec.rz
200 OK
GET https://index.rubygems.org/info/rails
200 OK
GET https://index.rubygems.org/info/railties
200 OK
GET https://index.rubygems.org/info/actionpack
200 OK
GET https://index.rubygems.org/info/activesupport
200 OK
GET https://index.rubygems.org/info/method_source
200 OK
GET https://index.rubygems.org/info/rake
200 OK
GET https://index.rubygems.org/info/thor
200 OK
GET https://index.rubygems.org/info/zeitwerk
200 OK
GET https://index.rubygems.org/info/actionview
200 OK
GET https://index.rubygems.org/info/rack
200 OK
GET https://index.rubygems.org/info/rack-test
200 OK
GET https://index.rubygems.org/info/rails-dom-testing
200 OK
GET https://index.rubygems.org/info/rails-html-sanitizer
200 OK
GET https://index.rubygems.org/info/concurrent-ruby
200 OK
GET https://index.rubygems.org/info/i18n
200 OK
GET https://index.rubygems.org/info/minitest
200 OK
GET https://index.rubygems.org/info/tzinfo
200 OK
GET https://index.rubygems.org/info/builder
200 OK
GET https://index.rubygems.org/info/erubi
200 OK
GET https://index.rubygems.org/info/nokogiri
200 OK
GET https://index.rubygems.org/info/json
200 OK
GET https://index.rubygems.org/info/mini_portile
200 OK
GET https://index.rubygems.org/info/mini_portile2
200 OK
GET https://index.rubygems.org/info/pkg-config
200 OK
GET https://index.rubygems.org/info/racc
200 OK
GET https://index.rubygems.org/info/thread_safe
200 OK
GET https://index.rubygems.org/info/loofah
200 OK
GET https://index.rubygems.org/info/crass
200 OK
GET https://index.rubygems.org/quick/Marshal.4.8/rack-2.2.3.1.gemspec.rz
200 OK
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/MIT-LICENSE
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/README.md
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/Rakefile
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.alternates.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.cyrillic.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.extra.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.greek.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.latin-ext.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.latin.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.symbols.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-italic.vietnamese.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.alternates.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.cyrillic.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.extra.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.greek.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.latin-ext.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.latin.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.symbols.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/fonts/Inter-roman.vietnamese.var.woff2
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/app/assets/stylesheets/inter-font.css
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/exe/tailwindcss
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/controller/controller_generator.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/controller/templates/view.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/mailer/mailer_generator.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/mailer/templates/view.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/mailer/templates/view.text.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/scaffold_generator.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/templates/_form.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/templates/edit.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/templates/index.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/templates/new.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/templates/partial.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/install/Procfile.dev
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/install/application.tailwind.css
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/install/dev
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/install/tailwind.config.js    
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/install/tailwindcss.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tailwindcss-rails.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tailwindcss/engine.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tailwindcss/upstream.rb       
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tailwindcss/version.rb        
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tasks/build.rake
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tasks/clobber.rake
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/tailwindcss-rails-2.0.8/lib/tasks/install.rake
C:/Ruby31-x64/bin/tailwindcss
C:/Ruby31-x64/bin/tailwindcss.bat
Successfully installed tailwindcss-rails-2.0.8
Parsing documentation for tailwindcss-rails-2.0.8
Parsing sources...
100% [24/24]  lib/tasks/install.rake
Installing ri documentation for tailwindcss-rails-2.0.8
Done installing documentation for tailwindcss-rails after 1 seconds
1 gem installed

**Comment by devcamke** [comment]
The output from gem env

PS C:\dev\kamau\bin> gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.12
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x64-mingw-ucrt]
  - INSTALLATION DIRECTORY: C:/Ruby31-x64/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: C:/Users/Dennis Kamau/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: C:/Ruby31-x64/bin/ruby.exe
  - GIT EXECUTABLE: C:\Program Files\Git\cmd/git.EXE
  - EXECUTABLE DIRECTORY: C:/Ruby31-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Dennis Kamau/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x64-mingw-ucrt
  - GEM PATHS:
     - C:/Ruby31-x64/lib/ruby/gems/3.1.0
     - C:/Users/Dennis Kamau/.local/share/gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\Actian\PSQL\bin\
     - C:\Program Files\Actian\PSQL\bin\
     - C:\Program Files (x86)\RSA SecurID Token Common
     - C:\Program Files\RSA SecurID Token Common
     - C:\Python310\Scripts\
     - C:\Python310\
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - C:\Program Files\nodejs\
     - C:\ProgramData\chocolatey\bin
     - C:\Program Files (x86)\HP\Common\HPDestPlgIn\
     - C:\Program Files (x86)\HP\IdrsOCR_15.3.1129.0\
     - C:\Program Files (x86)\Yarn\bin\
     - C:\Program Files\erl-24.1.7\bin
     - C:\Program Files (x86)\Elixir\bin
     - C:\WINDOWS\system32\config\systemprofile\.mix\escripts
     - C:\Program Files\Docker\Docker\resources\bin
     - C:\ProgramData\DockerDesktop\version-bin
     - C:\Program Files\Git\cmd
     - C:\Users\Dennis Kamau\.cargo\bin
     - C:\Ruby31-x64\bin
     - C:\Program Files\RSA SecurID Token Common\
     - C:\Users\Dennis Kamau\AppData\Local\Yarn\bin
     - C:\Program Files\heroku\bin
     - C:\Users\Dennis Kamau\AppData\Local\Programs\Microsoft VS Code\bin
     - C:\Program Files\JetBrains\IntelliJ IDEA Educational Edition 2022.1\bin

**Comment by devcamke** [comment]
The output from bundle env

PS C:\dev\kamau\bin> bundle env
## Environment

```
Bundler       2.3.14
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [x64-mingw-ucrt]
  Full Path   C:/Ruby31-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.3.12
  Gem Home    C:/Ruby31-x64/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/Dennis Kamau/.local/share/gem/ruby/3.1.0;C:/Ruby31-x64/lib/ruby/gems/3.1.0  User Home   C:/Users/Dennis Kamau
  User Path   C:/Users/Dennis Kamau/.local/share/gem/ruby/3.1.0
  Bin Dir     C:/Ruby31-x64/bin
Tools
  Git         2.36.1.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-05-18
Git SHA           467ad58a7c
Released Version  true
```

## Gemfile

### ../Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.3"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem "tailwindcss-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Sass to process CSS
# gem "sassc-rails"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### ../Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.0.3)
      actionpack (= 7.0.3)
      activesupport (= 7.0.3)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (7.0.3)
      actionpack (= 7.0.3)
      activejob (= 7.0.3)
      activerecord (= 7.0.3)
      activestorage (= 7.0.3)
      activesupport (= 7.0.3)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.0.3)
      actionpack (= 7.0.3)
      actionview (= 7.0.3)
      activejob (= 7.0.3)
      activesupport (= 7.0.3)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.0)
    actionpack (7.0.3)
      actionview (= 7.0.3)
      activesupport (= 7.0.3)
      rack (~> 2.0, >= 2.2.0)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (7.0.3)
      actionpack (= 7.0.3)
      activerecord (= 7.0.3)
      activestorage (= 7.0.3)
      activesupport (= 7.0.3)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.0.3)
      activesupport (= 7.0.3)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (7.0.3)
      activesupport (= 7.0.3)
      globalid (>= 0.3.6)
    activemodel (7.0.3)
      activesupport (= 7.0.3)
    activerecord (7.0.3)
      activemodel (= 7.0.3)
      activesupport (= 7.0.3)
    activestorage (7.0.3)
      actionpack (= 7.0.3)
      activejob (= 7.0.3)
      activerecord (= 7.0.3)
      activesupport (= 7.0.3)
      marcel (~> 1.0)
      mini_mime (>= 1.1.0)
    activesupport (7.0.3)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    bindex (0.8.1)
    bootsnap (1.11.1)
      msgpack (~> 1.2)
    builder (3.2.4)
    capybara (3.37.1)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    childprocess (4.1.0)
    concurrent-ruby (1.1.10)
    crass (1.0.6)
    debug (1.5.0)
      irb (>= 1.3.6)
      reline (>= 0.2.7)
    digest (3.1.0)
    erubi (1.10.0)
    globalid (1.0.0)
      activesupport (>= 5.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    importmap-rails (1.1.0)
      actionpack (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.5.11)
    irb (1.4.1)
      reline (>= 0.3.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.18.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.2)
    mini_portile2 (2.8.0)
    minitest (5.15.0)
    msgpack (1.5.2)
    net-imap (0.2.3)
      digest
      net-protocol
      strscan
    net-pop (0.1.1)
      digest
      net-protocol
      timeout
    net-protocol (0.1.3)
      timeout
    net-smtp (0.3.1)
      digest
      net-protocol
      timeout
    nio4r (2.5.8)
    nokogiri (1.13.6)
      mini_portile2 (~> 2.8.0)
      racc (~> 1.4)
    nokogiri (1.13.6-x64-mingw-ucrt)
      racc (~> 1.4)
    pg (1.3.5)
    pg (1.3.5-x64-mingw-ucrt)
    public_suffix (4.0.7)
    puma (5.6.4)
      nio4r (~> 2.0)
    racc (1.6.0)
    rack (2.2.3.1)
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails (7.0.3)
      actioncable (= 7.0.3)
      actionmailbox (= 7.0.3)
      actionmailer (= 7.0.3)
      actionpack (= 7.0.3)
      actiontext (= 7.0.3)
      actionview (= 7.0.3)
      activejob (= 7.0.3)
      activemodel (= 7.0.3)
      activerecord (= 7.0.3)
      activestorage (= 7.0.3)
      activesupport (= 7.0.3)
      bundler (>= 1.15.0)
      railties (= 7.0.3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.4.2)
      loofah (~> 2.3)
    railties (7.0.3)
      actionpack (= 7.0.3)
      activesupport (= 7.0.3)
      method_source
      rake (>= 12.2)
      thor (~> 1.0)
      zeitwerk (~> 2.5)
    rake (13.0.6)
    regexp_parser (2.4.0)
    reline (0.3.1)
      io-console (~> 0.5)
    rexml (3.2.5)
    rubyzip (2.3.2)
    selenium-webdriver (4.2.0)
      childprocess (>= 0.5, < 5.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sprockets (4.0.3)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    stimulus-rails (1.0.4)
      railties (>= 6.0.0)
    strscan (3.0.3)
    tailwindcss-rails (2.0.8)
      railties (>= 6.0.0)
    tailwindcss-rails (2.0.8-x64-mingw32)
      railties (>= 6.0.0)
    thor (1.2.1)
    timeout (0.3.0)
    turbo-rails (1.1.1)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2022.1)
      tzinfo (>= 1.0.0)
    web-console (4.2.0)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.0.0)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0)
    websocket (1.2.9)
    websocket-driver (0.7.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.5.4)

PLATFORMS
  x64-mingw-ucrt
  x64-mingw32

DEPENDENCIES
  bootsnap
  capybara
  debug
  importmap-rails
  jbuilder
  pg (~> 1.1)
  puma (~> 5.0)
  rails (~> 7.0.3)
  selenium-webdriver
  sprockets-rails
  stimulus-rails
  tailwindcss-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 3.1.1p18

BUNDLED WITH
   2.3.14
```

**Comment by flavorjones** [comment]
Ah, interesting, `gem install` is downloading the vanilla "ruby" platform gem and not the native one. This may be because the platform string is `x64-mingw-ucrt` and not `x64-mingw32`.

I think the answer will be for us to publish the same binary executable as a `x64-mingw-ucrt` gem, but let me fire up a VM and verify that diagnosis.

**Comment by flavorjones** [comment]
PR #173 will fix this once it's merged and a new release is cut.

**Comment by migobach** [comment]
I am having a similar issue with `-darwin-21` as my listed platform. @flavorjones any insight appreciated as to why when running the app locally, I consistently get the error `ERROR: tailwindcss-rails does not support the -darwin platform`, particularly when following the install instructions with tailwind doesn't seem to correct the issue. Any help appreciated!

**Comment by devcamke** [comment]
Thank you @flavorjones this resolved my issue and now everythings works fine.
