### ISSUE TITLE
spaces not handled in directory names on windows

### ISSUE THREAD

**Issue by deyemiobaa** [rails/tailwindcss-rails#184]
### Discussed in https://github.com/tailwindlabs/tailwindcss/discussions/8915

<div type='discussions-op-text'>

<sup>Originally posted by **deyemiobaa** July 21, 2022</sup>
Hello, I'm trying to set up a new rails project with `rails new my_app --css tailwind` && `rails new my_app --css=tailwind` but I keep getting an error
![image](https://user-images.githubusercontent.com/55185309/180105856-9ccf9863-e711-4f00-af84-12420a0110f1.png)

This same error also exists if I try to add tailwind-CSS manually using the steps specified in the documentation
![image](https://user-images.githubusercontent.com/55185309/180106000-913b8f61-3599-499e-aebb-47fe4b527e46.png)

I use a Windows 10 PC</div>

**Comment by iliatalebzade** [comment]
The same thing is happening to me too and I'm using WSL Ubuntu on top of Windows10

**Comment by deyemiobaa** [comment]
@iliatalebzade I found found solution later.
I used ruby installer and cssbundling-rails

**Comment by rafaelfranca** [comment]
This is a bug in how the Windows paths are generated and escaped by the shell. The space in the folder name is what is making the tailwindcss CLI confused.

Which version of tailwindcss-rails is being used? Because this should have be fixed in https://github.com/rails/tailwindcss-rails/pull/176

**Comment by iliatalebzade** [comment]
the version I used was 3.1.8

**Comment by rafaelfranca** [comment]
Of tailwindcss-rails? There isn't a 3.1.8 version https://rubygems.org/gems/tailwindcss-rails

**Comment by iliatalebzade** [comment]
Please excuse the delay, it's:
2.0.12

**Comment by flavorjones** [comment]
I think the issue here might be the `tailwindcss` wrapper script isn't preserving the quotes ...

This bug existing is more evidence that we really do need test coverage for the rake tasks. I'm going to take some time today to do that, so that we have a failing test for this that we can fix.

**Comment by flavorjones** [comment]
Fix for this is up at #197
