### ISSUE TITLE
Decouple `tailwindcss-rails` releases from Tailwind

### ISSUE THREAD

**Issue by TastyPi** [rails/tailwindcss-rails#187]
Mentioned in #186 

It would be nice to not have to wait for a new release of tailwindcss-rails to use the latest Tailwind version. This would involve making it possible to provide the tailwindcss executable separately.

Alternatively, maybe setting up an automation that updates the Tailwind version and pushes a new release would be possible.

**Comment by dhh** [comment]
Need to make the versioning stable, but like the idea of an automated release process!

**Comment by flavorjones** [comment]
I'll work on an automated process of some kind on a (figurative) background thread. In the meantime I'll commit to shipping manual PRs when a new version drops upstream.

**Comment by flavorjones** [comment]
I'm going to close this, we've made timely releases containing 3.2.0 and 3.2.1. Someday we may automate.
