### ISSUE TITLE
Rails "test:system" Rake task doesn't run any tests

### ISSUE THREAD

**Issue by chrisgibson** [rails/tailwindcss-rails#188]
I created a new Rails application (with v7.0.3.1) and generated a new system test. 

With v2.0.11 of the tailwindcss-rails gem, `bin/rails test:system` prints the Tailwind CSS compilation output and exits (without running any tests).

If I downgrade to v2.0.10, it prints the Tailwind CSS compilation output and proceeds to run the tests.

I believe the use of `exec` (introduced in https://github.com/rails/tailwindcss-rails/pull/181) has changed the behavior when multiple Rake tasks are involved as is the case when the `test:prepare` Rails Rake task is enhanced with `tailwindcss:build`. The process is exiting after the Tailwind CSS compilation.

**Comment by flavorjones** [comment]
@chrisgibson Yup, what you're describing makes sense and we shouldn't be using exec. I'll explore replacing it putting some tests in place to prevent regressions in the rake tasks.

**Comment by flavorjones** [comment]
Looks like a PR to address this has been opened at #189

**Comment by flavorjones** [comment]
[Release v2.0.12 · rails/tailwindcss-rails](https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.12) addresses this.

**Comment by chrisgibson** [comment]
Confirmed. Thanks @flavorjones!
