### ISSUE TITLE
Install fails on rails without webpack

### ISSUE THREAD

**Issue by r03** [rails/tailwindcss-rails#19]
When I run these steps:
```
rails new demo —database=postgresql --skip-jbuilder --skip-webpack-install
cd demo
./bin/bundle add tailwindcss-rails
./bin/rails tailwindcss:install
```
I get this error:
```
rails aborted!
Webpacker configuration file not found /Users/roeland/dev/demo/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /Users/roeland/dev/demo/config/webpacker.yml
/Users/roeland/dev/demo/bin/rails:5:in `<top (required)>'
/Users/roeland/dev/demo/bin/spring:10:in `require'
/Users/roeland/dev/demo/bin/spring:10:in `block in <top (required)>'
/Users/roeland/dev/demo/bin/spring:7:in `<top (required)>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - /Users/roeland/dev/demo/config/webpacker.yml
/Users/roeland/dev/demo/bin/rails:5:in `<top (required)>'
/Users/roeland/dev/demo/bin/spring:10:in `require'
/Users/roeland/dev/demo/bin/spring:10:in `block in <top (required)>'
/Users/roeland/dev/demo/bin/spring:7:in `<top (required)>'
Tasks: TOP => app:template
(See full trace by running task with --trace)
```

I installed without webpack because of this in de README: `When run on an app using the just the asset pipeline,` 

I'm a Rails beginner so maybe I'm doing things wrong?

**Comment by dhh** [comment]
You need —skip-javascript 👍

**Comment by jontebol** [comment]
If someone else has trouble with this, you might have to manually remove `webpacker` from the Gemfile even though you've used `--skip-javascript` and `--skip-webpack-install`. At least I did on Rails 6.0.3.5.

**Comment by roelandmoors** [comment]
@jontebol , I had the same problem, but the problem was a wrong dash character. (copy/paste?)

This works:
`rails new portefeuille --database=postgresql --skip-jbuilder --skip-webpack-install --skip-javascript`

This doesn't:
`rails new portefeuille -—database=postgresql --skip-jbuilder --skip-webpack-install -—skip-javascript`
