### ISSUE TITLE
Error in "Compile initial Tailwind build" stage of "rails new" command that has --css tailwind

### ISSUE THREAD

**Issue by iliatalebzade** [rails/tailwindcss-rails#193]
when running the command rails new everything works fine until the part where this part comes: 
Compile initial Tailwind build
    run  rails tailwindcss:build from "."
and then gives some error outputs 

![Capture](https://user-images.githubusercontent.com/64826533/187890311-0b0916c1-4f68-4d34-8836-b3ce900f4978.PNG)

the other 
The odd thing that's happening is that when you open the project there's a bizarre file added:

![Capture2](https://user-images.githubusercontent.com/64826533/187890672-e97f8727-ebcd-4d54-a6ff-0d9e22181605.PNG)

To my knowledge, I haven't modified, installed or uninstalled any packages regarding tailwind or tailwind-rails but this command was working just fine before This happened.

**Comment by flavorjones** [comment]
Hi @iliatalebzade, sorry you're having problems.

Can you please provide more information about your system? This looks like there may be some platform confusion -- `ELF: not found` sometimes indicates that a binary executable is being run as if it were a shell script.

**Comment by flavorjones** [comment]
This may be fixed by #197.

**Comment by iliatalebzade** [comment]
Greetings, thank you for the fix!

**Comment by flavorjones** [comment]
@iliatalebzade please wait for the next release of tailwindcss-rails and if you're still having problems, please open a new issue and we can start debugging from there.

**Comment by iliatalebzade** [comment]
Gotta mention how great you guys are addressing this problem this quick, I'll wait for the next release,
thanks again for your response!

**Comment by flavorjones** [comment]
v2.0.13 is out, please give it a try.
