### ISSUE TITLE
Provide Webpack setup path

### ISSUE THREAD

**Issue by dhh** [rails/tailwindcss-rails#2]
Like `turbo-rails`, it would be nice if this gem could double as an install script for Tailwind CSS on Webpack. If Webpack is detected, we run `tailwindcss:install:webpack`.

**Comment by JulianPasquale** [comment]
I'd like to mention that trying to install Tailwind CSS with Webpacker manually, got [this issue](https://github.com/rails/webpacker/issues/2784).
