### ISSUE TITLE
group-hover classes are not removed

### ISSUE THREAD

**Issue by andersklenke** [rails/tailwindcss-rails#20]
After https://github.com/rails/tailwindcss-rails/commit/8af7bfcb1a11d7cd63a3be4a6a3c53a9a37df679 group-hover classes, `group-hover:text-gray-900` for example, are not purged. 

This adds a substantial amount of classes to the outputted css. 

Unfortunately my regex skills are not strong enough to fix it.

(Originally created a [comment](https://github.com/rails/tailwindcss-rails/issues/15) but a new issue is probably more visible to people. )

**Comment by kaspth** [comment]
Possible to open a PR with a failing test? Can try to fiddle with rubular.com to help sift the regex tweaks needed.

**Comment by andersklenke** [comment]
Sure! Will open a failing test pr tomorrow
