### ISSUE TITLE
rails assets:precompile gives error: tailwindcss-rails does not support the x86_64-linux platform

### ISSUE THREAD

**Issue by deflexor** [rails/tailwindcss-rails#200]
Dockerfile:
```
FROM ruby:3.1.2-alpine
WORKDIR /app
COPY . .
RUN apk add --update --no-cache build-base gcc g++ git less tzdata \
  libstdc++ libffi-dev libc-dev sqlite-dev postgresql-dev build-base gcompat
RUN gem install bundler
RUN bundle lock --add-platform x86_64-linux
RUN bundle --verbose
ENV RAILS_ENV=production
RUN bundle exec rails assets:clean assets:precompile
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]
```
Results in error:

Tailwindcss::Commands::UnsupportedPlatformException: tailwindcss-rails does not support the x86_64-linux platform

**Comment by flavorjones** [comment]
Hi, sorry you're having a problem, I'll try to help.

This gem absolutely supports alpine, so we'll need more information about your Rails app. Can you please share the output of `bundle env` in this container on your rails application?

**Comment by gucki** [comment]
@flavorjones I just hit the same issue with a new (minimal) rails 7.0.4 application. It seems it only occurs when using rubygems 3.3.22. It does not occur when using rubygems 3.3.7 (but this version causes https://github.com/rubygems/rubygems/issues/5351).  In all cases using ruby:3.1-alpine as base image.

**Comment by flavorjones** [comment]
@gucki I think you're describing https://github.com/rubygems/rubygems/issues/5914? But I'm only guessing because I don't know what command you're running (`gem` or `bundle`) or other info about your system

@deflexor Can you please share the output of `bundle env` in this container on your rails application?

**Comment by flavorjones** [comment]
I see ... just to confirm, the native gem is installing fine but you're getting this error from the `tailwindcss` wrapper. Interesting. I'll dig in a bit more.

**Comment by flavorjones** [comment]
OK, reproduced at https://github.com/rails/tailwindcss-rails/actions/runs/3084115065/jobs/4985885770

**Comment by flavorjones** [comment]
OK, I've identified the problem upstream in rubygems, and bug has been filed here: https://github.com/rubygems/rubygems/issues/5938

**Comment by flavorjones** [comment]
[Release v2.0.14 / 2022-09-19 · rails/tailwindcss-rails](https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.14) has been released which works around this bug.

**Comment by gucki** [comment]
@flavorjones Thank you! I can confirm it fixed the issue for me.
