### ISSUE TITLE
Tailwind Classes not compiled using ViewComponents

### ISSUE THREAD

**Issue by sergitejada** [rails/tailwindcss-rails#201]
I have been testing ViewComponts and I found this ViewComponts + Tailiwnd guide.

[Example](https://orbit.love/blog/building-a-component-library-in-rails-with-storybook)
The guide uses a CDN to use tailwind and everything works fine.

My problem is that using tailwindcss-rails the tailwind classes that are injected from a component are not rendered in the view.

I start server from Procfile
![image](https://user-images.githubusercontent.com/49126831/190213054-771e5acc-498d-40bd-a189-b752df3e143e.png)

My tailwind.config:
![image](https://user-images.githubusercontent.com/49126831/190212912-24947791-609e-40f2-ac99-7f3afb9a231a.png)

My component:
![image](https://user-images.githubusercontent.com/49126831/190213250-660d314c-c3b4-4601-bf52-4e8f5725d798.png)

Component view: 
![image](https://user-images.githubusercontent.com/49126831/190213347-bd16d2e3-69b7-440c-928b-8d4aa2549ee9.png)

![image](https://user-images.githubusercontent.com/49126831/190213430-2fa351b0-3421-4072-9d8f-93395b29e49f.png)

Error:
![image](https://user-images.githubusercontent.com/49126831/190213590-117bea5c-df6f-48d0-affb-a6fa49f26033.png)

Classes are loaded in Html but not in css

I know where the error is but I can't find a solution without having to use a tailwind CDN.

PD: I have also used rails assets:clobber

**Comment by rafaelfranca** [comment]
This seems like tailwind not recognizing those classes are being used and removing them from the bundle. I think you also need to tell tailwind to check the component ruby files in the `content:` config in your `tailwind.config`

**Comment by rafaelfranca** [comment]
https://tailwindcss.com/docs/content-configuration#configuring-source-paths

**Comment by fc-anjos** [comment]
Make sure to add the components folder in the paths array to Tailwind config, as seen on your second screenshot.


`config/tailwind.config.js`
```
module.exports = {
  content: [
    './public/*.html',
    './app/helpers/**/*.rb',
    './app/javascript/**/*.js',
    './app/views/**/*.{erb,haml,html,slim}',
    './app/components/**/*' # This is the new Entry
  ],
  ```
