### ISSUE TITLE
Error: "wrong number of arguments (given 3, expected 1)" after install

### ISSUE THREAD

**Issue by modusss** [rails/tailwindcss-rails#206]
Hello,

I installed on 
 - Rails 7.0.1
 - Ruby Ruby 3.0.0

Using these command:
bundle add tailwindcss-rails
rails tailwindcss:install

And it shows this error on my rails app:

<img width="1216" alt="Screen Shot 2022-09-29 at 16 49 18" src="https://user-images.githubusercontent.com/20300214/193128131-3b4e3654-f1cd-4d80-8a4f-0ab33cfe7955.png">

I installed 2 times and restarted the server several times and the same error keeps going.

**Comment by adamdawkins** [comment]
I'm also having this issue, but not in development, only with `RAILS_ENV=test rake assets:precompile` or `RAILS_ENV=production rake assets:precompile`

**Comment by adamdawkins** [comment]
It looks like it could just be that we're missing some commas in the `rgb` output:

```
background-color: rgb(0 166 81/var(--tw-bg-opacity));
```
is the line my compilation is complaining about.
