### ISSUE TITLE
armv7l-linux support

### ISSUE THREAD

**Issue by dillonhafer** [rails/tailwindcss-rails#216]

**Comment by flavorjones** [comment]
Hi, the gem does not currently support this platform, but it looks like we _could_ since the [upstream](https://github.com/tailwindlabs/tailwindcss/releases) releases a `tailwindcss-linux-armv7` binary executable.

I can work on it this week. Can you confirm for me what your platform looks like by responding with the output from `gem env`? The platform string in particular is the key piece of information I don't currently have.

**Comment by dillonhafer** [comment]
```
dillon@raspberrypi:/var/www/rails-api/current# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [armv7l-linux-eabihf]
  - INSTALLATION DIRECTORY: /home/dillon/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /home/dillon/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /home/dillon/.asdf/installs/ruby/3.1.2/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/dillon/.asdf/installs/ruby/3.1.2/bin
  - SPEC CACHE DIRECTORY: /home/dillon/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/dillon/.asdf/installs/ruby/3.1.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - armv7l-linux-eabihf
  - GEM PATHS:
     - /home/dillon/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
     - /home/dillon/.local/share/gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/dillon/.asdf/installs/ruby/3.1.2/bin
     - /home/dillon/.asdf/shims
     - /home/dillon/.asdf/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

**Comment by dillonhafer** [comment]
Currently, I'm monkey-patching the gem as part of my deploy process by opening the `Tailwindcss::Commands` module and changing the `#executable` method to return `system("which tailwindcss")` to use the system installed CLI

**Comment by flavorjones** [comment]
Thanks for the additional info. It should be easy to add this platform, but it may be harder to _test_ it. I'll take a look this week!

**Comment by flavorjones** [comment]
I've got a PR at #218 that looks like it works. It should go green shortly, if so I can merge and cut a release tomorrow.

**Comment by dillonhafer** [comment]
Wow, thanks for all your work, I really appreciate the time that went into this. 🎉

**Comment by dillonhafer** [comment]
I just ran a deployment and it worked perfectly! Thank you! ❤️
