### ISSUE TITLE
Pointing to the tailwindcss executable

### ISSUE THREAD

**Issue by TheNeikos** [rails/tailwindcss-rails#224]
I'm running NixOs and due to multiple reasons I cannot install platform-native gems. However, I _can_ install the tailwindcss executable on its own. However, this gem does not try checking PATH if the included version does not exist.

I understand that this is probably for easier maintenance and is a good idea. However, could a configuration/escape hatch be added that would allow me to point it at the tailwindcss executable? The onus would be on me to make sure the versions match up etc...

This would make it possible to use on NixOS while still keeping the niceties of the gem.

**Comment by flavorjones** [comment]
I've been waiting for someone with a specific use case to ask for this! Yes, we can absolutely figure something out.

What is the user experience you're expecting? Is it:

- install the "ruby" platform gem (not any of the native platform gems)
- have the shim check your `$PATH` for another `tailwindcss` executable and run that if it finds one

or something else entirely?

**Comment by TheNeikos** [comment]
Nope that would directly solve the issue!

**Comment by flavorjones** [comment]
:thinking: OK, let me see what I can do.

**Comment by flavorjones** [comment]
See PR #226

**Comment by flavorjones** [comment]
See [Release v2.0.26 / 2023-03-30 · rails/tailwindcss-rails](https://github.com/rails/tailwindcss-rails/releases/tag/v2.0.26) which provides a way to use a locally-installed tailwindcss executable. (See README for details.)
