### ISSUE TITLE
Does not support scss

### ISSUE THREAD

**Issue by KinWang-2013** [rails/tailwindcss-rails#228]
I tried creating a file `application.tailwind.scss` but it does not work on rake assets:precompile. tried changing the code in gem from

```
def compile_command(debug: false, **kwargs)
  [
    executable(**kwargs),
    "-i", Rails.root.join("app/assets/stylesheets/application.tailwind.css").to_s,
    "-o", Rails.root.join("app/assets/builds/tailwind.css").to_s,
    "-c", Rails.root.join("config/tailwind.config.js").to_s,
  ].tap do |command|
    command << "--minify" unless debug
  end
end
```

to: 

```
def compile_command(debug: false, **kwargs)
  [
    executable(**kwargs),
    "-i", Rails.root.join("app/assets/stylesheets/application.tailwind.scss").to_s,
    "-o", Rails.root.join("app/assets/builds/tailwind.css").to_s,
    "-c", Rails.root.join("config/tailwind.config.js").to_s,
  ].tap do |command|
    command << "--minify" unless debug
  end
end
```

and it compiled, notice the path application.tailwind.scss, and application.tailwind.css  can we add a support for scss too?

**Comment by flavorjones** [comment]
Hi! Thanks for suggesting this.

I'm not a Sass/SCSS user, but my understanding is that it won't work with TailwindCSS in most cases with without additional preprocessing being set up. This is discussed a bit at https://tailwindcss.com/docs/using-with-preprocessors#using-sass-less-or-stylus

**Comment by KinWang-2013** [comment]
Hello @flavorjones Thank you for your response.
