### ISSUE TITLE
Ship scaffold generator that uses a nice Tailwind design

### ISSUE THREAD

**Issue by dhh** [rails/tailwindcss-rails#23]
The default Rails scaffold is plain to a fault. Let's ship some scaffold templates with this gem that uses Tailwind to demonstrate it.

**Comment by gobijan** [comment]
Okay just to get the discussion started I think we first need to agree on a few things:

1. Do we want to use table or div under the hood?
**Divs** make it easier to adjust to mobile and also for turbo-rails to substitute responses if I remember correctly.
**Tables** are more structured and offer some kind of easy to add sortability (for example https://datatables.net or https://www.w3schools.com/w3js/w3js_sort.asp or whatever).

2. Do we want to show all properties by default or say only the first 4 (or whatever number)?
If we show all tables might really be the wrong approach given they are a pain on mobile.
Giving it a thought definition lists might be a feasible approach. Any opinion on that?

3. What about the actions per item?
Do we want to show all actions on every item or do we want to make an item clickable and show the edit or delete functionality only on the details page? This would provide less visual clutter.

4. Do we want to add javascript functionality out of the box?
Not sure if we want to use dropdowns with additional actions like edit or delete. I would say no but let me know what you think.

5. Do we have any color preferences? 
Rails uses a lot of red but for example a create item button is in western color usage more of a dangerous thing.

I played around a little and came up with this. It is still not nearly refined but uses definition list under the hood as an idea.
![Bildschirmfoto 2021-01-24 um 22 48 13](https://user-images.githubusercontent.com/49339/105644800-cbf78100-5e97-11eb-8f01-c794fc242290.png)

Tailwind UI gave me the idea of stacked lists BUT how to choose what to show or not, when there are many items?
See screenshot:
![Bildschirmfoto 2021-01-24 um 23 00 32](https://user-images.githubusercontent.com/49339/105644845-2bee2780-5e98-11eb-8225-00dab290c9e4.png)

**Comment by hahmed** [comment]
@gobijan maybe worth creating a PR that adds the scaffolds and the basic styles then the discussion can happen on the PR?

We should be showing all the records by default and perhaps skip the colours in the initial PR (links commonly have blue so that should be good?)

**Comment by dixpac** [comment]
@dhh you want this scaffold generator to override default rails generator(`bin/rails g scaffold`), or with different name such as `bin/rails g tailwind_scaffold ...`?

**Comment by dhh** [comment]
I'd like to see it overridden. If you have tailwind installed, you want tailwind scaffolds.

**Comment by dixpac** [comment]
Alright! I'm on it 😄

**Comment by guledali** [comment]
Would be cool to see a pairing between @adamwathan and @dhh like the one made for Tuple, 

https://www.youtube.com/watch?v=SK27unk2UuI&ab_channel=AdamWathan


@dhh Maybe someone should consult Steve Schoger @sschoger on this one as well. He has really good eye for design, he would easily bring the design for rails scaffold to the **next level**

**Comment by dixpac** [comment]
@guledali  I've already contacted Adam and Tailwind team to help with this. Adam and the team are 👍🏼 to help shaping scaffold wit their official touch :)

**Comment by guledali** [comment]
I hope this becomes the default in Rails 7

**Comment by afomera** [comment]
Is anyone still actively working on this one?

**Comment by BakiVernes** [comment]
@afomera We are! Check out the PR.

**Comment by afomera** [comment]
Great, thanks @BakiVernes! I'll leave it for now :)

**Comment by gardnerapp** [comment]
Hello, I am very new to open source I've been looking to create a default scaffolding views for Tailwind for quiet some time and I would like to help work on this project . Where should I get started?

**Comment by dhh** [comment]
Already done in https://github.com/rails/tailwindcss-rails/pull/71 👍 Just need to find some time to review and I'll merge.

**Comment by yshmarov** [comment]
> @dhh you want this scaffold generator to override default(`bin/rails g scaffold`), or with the different name such as `bin/rails g tailwind_scaffold ...`?

if you are using tailwind, but do not want to use the provided tailwind scaffold templates, you can manually set the template engine like this:

```ruby
# config/application.rb
    config.generators.template_engine = :erb
```
