### ISSUE TITLE
Tailwind being set as the template engine

### ISSUE THREAD

**Issue by dinclas** [rails/tailwindcss-rails#246]
The project is overriding the project configuration to set tailwindcss as the template engine, as can be seen here.
https://github.com/rails/tailwindcss-rails/blob/781d840dcd9452e01fdbf10d491d9b8742a019be/lib/tailwindcss/engine.rb#L14

Should this really be done? I mean, tailwind is not a templating engine and this causes issues like https://github.com/heartcombo/simple_form/issues/1806 where libraries expect proper templating engines on this config.

Cheers

**Comment by samuelpismel** [comment]
For those who are affected by this. 

The workaround is to add this to `config/application.rb`:

```
# fixes tailwindcss-rails overwrite
config.generators.template_engine :erb
```

**Comment by lrjbrual** [comment]
@samuelpismel this work. thanks

**Comment by flavorjones** [comment]
I would welcome a PR that updated the README with this workaround, @samuelpismel

**Comment by pas256** [comment]
See discussion here: https://github.com/rails/tailwindcss-rails/pull/131
