### ISSUE TITLE
Need to add `config.assets.debug = true` to `development.rb` file

### ISSUE THREAD

**Issue by DogAndCode** [rails/tailwindcss-rails#251]
Hi, I have to add `config.assets.debug = true` to `development.rb` file because if not all the changes made on `application.tailwind.css` file dont work, like for example:

`@layer base {
  a {
    @apply text-red-500 underline
  }`

**Comment by flavorjones** [comment]
@DogAndCode Can you explain a bit more about what you're experiencing, so that I can try to reproduce it? The tailwind asset pipeline works fine for me in development regardless of this setting, so I need to understand what's different about your setup. (I'm using a vanilla Rails app after running `bin/rails tailwindcss:install`.)

**Comment by DogAndCode** [comment]
Hi @flavorjones, sure, I'm using on my app:

- Ruby 3.2.1
- Rails 7.0.4.2
- Tailwindcss-rails

I was having a problem. If I use the inline css on my `*html.erb` files it works correctly, but if I try to, instead of inline css, add base styles with on @layer base It doesn't work unless I  add `config.assets.debug = true` to `development.rb`.

This works:

<h1 class="font-bold text-4xl text-blue-500">Hello!</h1>

This doesn't (unless I set `config.assets = true`)

```@layer base {
  h1 {
    @apply font-bold text-4xl text-blue-500;
  }
}```

**Comment by bijanpuri** [comment]
I have the same issue. if I don't set this flag, styles that I'm specifying aren't appearing in the built tailwind.css file in development.

**Comment by geetfun** [comment]
Can also confirm that this was the case on my M1 Pro MBP.

FWIW, I have the same project set up on a Ubuntu 22.04 laptop, and this did not seem to be affected on that platform.

**Comment by reeganviljoen** [comment]
@geetfun I am having both of the above issues with a cleanly installed example on linux mint 20

**Comment by dlim87** [comment]
I can confirm this is also happening on WSL running on Ubuntu 22.04.2 LTS

**Comment by flavorjones** [comment]
Can someone please set up a gist or repo that reproduces what you're seeing? As I mentioned above, I need help to reproduce and diagnose the issue.

**Comment by truongduyng** [comment]
> I have the same issue. if I don't set this flag, styles that I'm specifying aren't appearing in the built tailwind.css file in development.

I have the same issue. It had no errors but only generated some styles not all what I used in my views

**Comment by reeganviljoen** [comment]
With a new all generated yesterday I am not experiencing this issue

**Comment by flavorjones** [comment]
Closing. If someone is having this issue, then please open a new issue with instructions on how to reproduce it.
