### ISSUE TITLE
tailwindcss-rails-2.0.29-x86_64-linux/exe/x86_64-linux/tailwindcss: Syntax error: word unexpected (expecting ")")

### ISSUE THREAD

**Issue by ror-surgeon** [rails/tailwindcss-rails#266]
i am installing in rails 7.0.4.3

**Comment by flavorjones** [comment]
@ror-surgeon Sorry you're having problems. The most likely explanation is that you have a syntax error in your local file `config/tailwind.config.js`.

Please take a careful look at that file, and if that's not the issue then please comment here with more information, including:
- the command you're running and the full output from that command
- the full contents of your `tailwind.config.js` file

**Comment by SkandarS0** [comment]
Hi I have the same problem, I am using WSL1 with a Ubuntu distro, 

![image](https://github.com/rails/tailwindcss-rails/assets/41797221/1c5596da-072d-4214-9deb-bf103603a3a8)
![image](https://github.com/rails/tailwindcss-rails/assets/41797221/00745745-776c-411b-913e-7f6adfd5a1fb)
![image](https://github.com/rails/tailwindcss-rails/assets/41797221/3f7dc903-2497-4dcb-b1c6-2bce5e10223a)

**Comment by SkandarS0** [comment]
after running both commands, a new file with gibberish name is created in the project root that has no content.
![image](https://github.com/rails/tailwindcss-rails/assets/41797221/78a898c2-21c3-44d0-b536-27a5e23fe2f8)
