### ISSUE TITLE
Intellisense does not work with rails/tailwindcss-rails

### ISSUE THREAD

**Issue by samsonmolou** [rails/tailwindcss-rails#29]
👋 ,

This is more of a question than an issue. I've been toying around with https://github.com/rails/tailwindcss-rails the other day and while it's working perfectly fine, the VSCode extension does not work, since with this there is no tailwind entry in the package.json and also no tailwind config in the project root. It's all hidden within the gem.

I was wondering what the supposed escape hatch for this would be, do you have any ideas? Current workaround would be to replicate the config within the project root and add tailwind to the package.json, even though it's not used. Is there any other way?

**Comment by dhh** [comment]
I think that's probably as good as its going to get!

**Comment by tomorrownull** [comment]
@samsonmolou 

You can try this extension ,The package.json and tailwind.config.js  is optional


https://marketplace.visualstudio.com/items?itemName=voorjaar.windicss-intellisense

This is my vscode configuration


```json
{ 
 "editor.quickSuggestions": {
    "strings": true
  },
  "files.associations": {
    "*.erb": "erb"
  },
  "windicss.includeLanguages": {
    "erb": "html"
  }
}
```
