### ISSUE TITLE
Browserslist: caniuse-lite is outdated. Please run: 21:49:24 css.1  |   npx update-browserslist-db@latest

### ISSUE THREAD

**Issue by beshoy23** [rails/tailwindcss-rails#294]
when running bin/dev i get this
Browserslist: caniuse-lite is outdated. Please run:
css.1  |   npx update-browserslist-db@latest

**Comment by flavorjones** [comment]
Duplicate of #283

**Comment by flavorjones** [comment]
Please note that this warning is quashed as of v3.3.2
