### ISSUE TITLE
use scaffold generate password class is nil

### ISSUE THREAD

**Issue by Kastrcn** [rails/tailwindcss-rails#304]
use scaffold generate password class is nil

```shell
rails g scaffold user username:string password:digest
```

<img width="1420" alt="image" src="https://github.com/rails/tailwindcss-rails/assets/19508899/5194a9a1-bff6-4c2e-ae57-1d9dda9305f8">

**Comment by flavorjones** [comment]
Thanks for opening this. Acknowledged, we should fix this. Currently the generated form looks like this live:

![image](https://github.com/rails/tailwindcss-rails/assets/8207/50a71969-a0fc-49be-8ff2-74d266b8b3f2)

**Comment by flavorjones** [comment]
Potential fix at #307
