### ISSUE TITLE
How do I get the color palette from the tailwind docs to work?

### ISSUE THREAD

**Issue by dmill** [rails/tailwindcss-rails#324]
### Discussed in https://github.com/rails/tailwindcss-rails/discussions/323

<div type='discussions-op-text'>

<sup>Originally posted by **dmill** February  1, 2024</sup>
Hello,

I'm working on a fresh rails 7 app with `-c tailwind`. I am unable to use the default colors documented [here](https://tailwindcss.com/docs/customizing-colors#using-the-default-colors). I've been googling around for this for awhile and nothing seems to work to get these colors to load. They work just find with a fresh react/next setup. Can anyone advise as to how to get these working in Rails without manually defining each color in `tailwind.config.js`?</div>

**Comment by flavorjones** [comment]
I've replied in #323
