### ISSUE TITLE
Anticipating Slow Compile Times

### ISSUE THREAD

**Issue by earnold** [rails/tailwindcss-rails#34]
Hi there!

Very excited to see this package. Adding tailwind to a new rails project is one of the first things I do. 

Locally, I've noticed that that a trivial change to application.js (or one of its dependencies) results in slow compile times: 

```
[Webpacker] Compiling...
[Webpacker] Compiled all packs in /Users/evan/Projects/scratch-pad/TailwindTester/public/packs
[Webpacker] Hash: b937b4359523d601173a
Version: webpack 4.46.0
Time: 5188ms
```

This is on an M1 MBP.

This is a [known issue](https://github.com/tailwindlabs/tailwindcss/issues/2820) for the interaction of postcss, web pack, and tailwind 2. While there are a few proposed work arounds on that issue, nothing seems super satisfactory. 

Do you have any plans for addressing this? If so, I'd love to help in anyway. Right now I'm scratching my head on how to address it.

**Comment by dhh** [comment]
You can use the webpack dev server. I believe that'll be faster. But otherwise, no. Not within the scope of what this gem is capable of doing.

The asset path version doesn't suffer from this (because there's no JS compile times!), but that's of course a larger change to make.
