### ISSUE TITLE
bin/dev doesn't work for me.

### ISSUE THREAD

**Issue by ZviadMestvi** [rails/tailwindcss-rails#354]
Hi, I want to use tailwindcss-rails, followed the instructions that are on here: [https://tailwindcss.com/docs/guides/ruby-on-rails]( https://tailwindcss.com/docs/guides/ruby-on-rails) but when running bin/dev nothing is happening, it just goes to the next line in terminal (powershell). I couldn't find anything helpful on the internet so I don't know if issue is on my side. 

Ruby version - 3.3.0
Rails  version - 7.1.3.2

**Comment by flavorjones** [comment]
@ZviadMestvi Sorry you're having problems. Can you help me reproduce what you're seeing? Have you read through the [README](https://github.com/rails/tailwindcss-rails/blob/main/README.md)?

**Comment by flavorjones** [comment]
Ah, I missed that you're using powershell. The `bin/dev` script requires `sh` (or `bash`). If you have one of those you should be able to run `sh bin/dev` or `bash bin/dev`

I hope this helps?

**Comment by ZviadMestvi** [comment]
I used Git bash and it worked, but only after changing the code in Procfile.dev from:

```
web: bin/rails server
css: bin/rails tailwindcss:watch 
```
to: 
web: rails server
css: rails tailwindcss:watch

Thanks for help.
