### ISSUE TITLE
Cannot run tailwindcss:install on 0.3.2

### ISSUE THREAD

**Issue by mborromeo** [rails/tailwindcss-rails#36]
Hi!

The `tailwindcss:install` command fails on a fresh Rails 6.1.1 application, while using version `0.3.2`.

> ./bin/rails tailwindcss:install
> Copying Tailwindcss JavaScript
> rails aborted!
> Thor::Error: Could not find "/Users/marco.borromeo/.rvm/gems/ruby-2.7.1/gems/tailwindcss-rails-0.3.2/lib/install/app/assets/javascripts" in any of your source paths. Your current source paths are:
> /Users/marco.borromeo/.rvm/gems/ruby-2.7.1/gems/railties-6.1.1/lib/rails/generators/rails/app/templates
> /Users/marco.borromeo/temp/demo/bin/rails:5:in `<top (required)>'
> /Users/marco.borromeo/temp/demo/bin/spring:10:in `require'
> /Users/marco.borromeo/temp/demo/bin/spring:10:in `block in <top (required)>'
> /Users/marco.borromeo/temp/demo/bin/spring:7:in `tap'
> /Users/marco.borromeo/temp/demo/bin/spring:7:in `<top (required)>'
> Tasks: TOP => app:template
> (See full trace by running task with --trace)`

Downgrading to `0.3.1` perfectly works.

**Comment by dhh** [comment]
Ugh. 0.3.2 got garbled. Pushed 0.3.3 and yanked 0.3.2. Thanks for the quick report!
