### ISSUE TITLE
Isn't compatible with rails main branch and unix systems

### ISSUE THREAD

**Issue by rodrigotoledo** [rails/tailwindcss-rails#410]
To integrate Tailwind with your Rails project, first, set your gem to the main branch by adding the following line to your Gemfile:

```
gem "tailwindcss-rails", github: "rails/tailwindcss-rails", branch: "main"
```

Afterward, run:

```
bundle update
```

Next, generate authentication with:

```
bin/rails generate authentication
bin/dev
```

### Error Encounter
You might encounter this error:

```
08:49:46 css.1  | bin/rails aborted!
08:49:46 css.1  | Tailwindcss::Commands::ExecutableNotFoundException: Cannot find the tailwindcss executable for x86_64-linux...
```

### Steps to Resolve:

1. Ensure you're using the latest Bundler version:

```bash
gem install bundler
bundle update --bundler
```

2. Add the platform to your Gemfile.lock:

```bash
bundle lock --add-platform x86_64-linux
bundle install
```

3. Check Bundler configuration: Ensure force_ruby_platform isn’t set to true:

```bash
bundle config
```

I already run the instructions but still an error.

**Comment by flavorjones** [comment]
This was fixed in https://github.com/rails/tailwindcss-rails/releases/tag/v2.7.7 yesterday.
