### ISSUE TITLE
Feature: install Tailwind plugins without npm

### ISSUE THREAD

**Issue by bradgessler** [rails/tailwindcss-rails#421]
Picking up from https://x.com/flavorjones/status/1846728744645300224...

To recap, I've had conversations with Rails devs who are confused why they have to install npm to add Tailwind plugins to a `tailwindcss-rails` app when using importmaps. For example, installing daisyUI requires npm: https://daisyui.com/docs/install/

I initially struggled building a mental model around this, but then I figured out that npm is used strictly for package management. I also had to add npm as a dependency to my build process to download and install tailwind plugins.

Ideally I could install Tailwind plugins without needing to introduce npm as a dependency to my project and could instead run a command similar to importmaps pinning to install the plugin. Is that something that would make sense in this library, tailwindcss-ruby, importmaps, or a different library/approach?

**Comment by flavorjones** [comment]
Can you please open this on flavorjones/tailwindcss-ruby, I'd like to keep this gem's responsibilities to only managing the integration between tailwind and rails, and afaict tailwind plugins are not a Rails-specific concern (e.g., I might want a plugin for a Jekyll app). Thanks.
