### ISSUE TITLE
Install broken without tailwind.config.js file?

### ISSUE THREAD

**Issue by jontebol** [rails/tailwindcss-rails#52]
The install script for this gem seems to require the presence of the `tailwind.config.js` file in `app/javascript/stylesheets` as referenced in the postcss.config.js file:

```js
module.exports = {
  plugins: [
    require('tailwindcss')("./app/javascript/stylesheets/tailwind.config.js"),
    ...
```

However, the installer doesn't create this file. I'm not well versed with webpacker, postcss or js in general so I don't really understand what's going on here, but I do know the only way I could get my install to work was by adding the `tailwind.config.js` file.

**Comment by jontebol** [comment]
Here's the output from the install command:

```
$ ./bin/rails tailwindcss:install
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.6-compliant syntax, but you are running 2.6.3.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
Installing Tailwind CSS
         run  yarn add tailwindcss@npm:@tailwindcss/postcss7-compat postcss@^7 autoprefixer@^9 from "."
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error tailwindcss@2.0.3: The engine "node" is incompatible with this module. Expected version ">=12.13.0". Got "10.23.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
      append  app/javascript/packs/application.js
Configuring Tailwind CSS
      create  app/javascript/stylesheets
      create  app/javascript/stylesheets/application.scss
         run  npx tailwindcss init from "."
npx: installed 80 in 5.199s
Cannot find module 'autoprefixer'
      insert  postcss.config.js
Default application.html.erb is missing!
        Add <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %> within the <head> tag in your custom layout.
```
I did the last step manually of course.

**Comment by wittawasw** [comment]
@jontebol There are number of issues with installing tailwindcss itself even without this gem.
Try  `yarn add tailwindcss@latest postcss@latest autoprefixer@latest`  and see if there are other errors from it.

**Comment by jontebol** [comment]
Thx @wittawasw. Since I opened this issue I've gotten much better at installing and configuring Tailwind both with and without webpacker, so for my own sake everything is fine (though I have reverted to not using the gem). I only opened the issue in case there was something missing in the installer. Feel free to close it if it's not of any value.

**Comment by dhh** [comment]
We've dropped webpack support from this gem. It's now exclusively intended for use with sprockets. Will introduce another, easy way to add TW to a webpack setup. But doesn't make sense to share it in the same gem.
