### ISSUE TITLE
Expected compile speed ?

### ISSUE THREAD

**Issue by defsdoor** [rails/tailwindcss-rails#55]
I'm getting ~7 seconds to compile an unaltered pipeline - is this typical as it severely impacts my workflow ?

My PC has a AMD Ryzen 9 3950X CPU - it's not a slow machine :|

**Comment by dhh** [comment]
Is this using webpacker or the asset pipeline? If webpacker, it is what it is. We don't really have any control over that.

**Comment by dmarcoux** [comment]
@defsdoor The short tutorial on https://hotwire.dev/ doesn't rely on webpacker, it's using the asset pipeline. This should get you started.

**Comment by leehericks** [comment]
Here’s how I start a new Hotwire app without webpacker.

`rails new myapp --skip-javascripts`

This skips webpacker, turbolinks and rails ujs.

Then add `gem 'hotwire-rails'` to your gemfile

`bundle install`
`rails hotwire:install`

This gives you a new rails app with a beautiful assets/javascripts folder with turbo and stimulus ready to go.

**Comment by defsdoor** [comment]
@leehericks thanks for this - giving it a go now.

BTW - the option is --skip-javascript 

@dmarcoux cheers

**Comment by leehericks** [comment]
@defsdoor Sorry, I swear I double checked that before posting 😅

**Comment by defsdoor** [comment]
All seems to work ok - thank you all.

I'm really interested in tailwind - is anyone aware of a project or efforts to create a sass based version ?  To me, using sass mixins is much more comfortable than postcss (and the beast it requires) rendering of the css.

I've already hit a need to add a minor customisation.
I guess I could do any customisations infrequently and generate a new tailwind.css outside of the development environment when needed.

**Comment by dhh** [comment]
Yes, if the app doesn't have webpacker, then it'll use the asset pipeline. --skip-javascript
