### ISSUE TITLE
Gem not compatible with rails 5+

### ISSUE THREAD

**Issue by gabrielboeker** [rails/tailwindcss-rails#56]
The game is unfortunately only available for rails 6 since the installation command forces the app to use webpacker which is based on rails 6. since the gem is also working with the asset pipeline, it should be no problem to convert to 5+. is it planned to be available for rails 5, or is there a workaround to make it work?

**Comment by dhh** [comment]
If you want to vet everything for Rails 5+, and do a PR to adapt, I'd be happy to take that.
