### ISSUE TITLE
There is no purger in my production.rb

### ISSUE THREAD

**Issue by tcgumus** [rails/tailwindcss-rails#57]
Hello,
After running rails tailwindcss:install there is no change in my `production.rb` file. 
Can you help me about this? It says that 

> The last option adds the purger compressor to config/environments/production.rb

 but there is no compressor enabled.

Should I add `Tailwindcss::Purger.purge tailwind_css` into my `production.rb` file

**Comment by japaternoster** [comment]
Hi @tcgumus, are you using the asset pipeline or Webpacker in your application? The gem will install differently depending on the approach:
- with Webpacker the installation will configure posts
- with the asset pipeline it will amend the `production.rb` file accordingly

My assumption is that you are using Webpacker, hence the installer didn't alter the `production.rb` and so is performing as expected. Please let us know if this is not the case.

**Comment by tcgumus** [comment]
Yes I was using webpacker. Thank you for the explanation. 👍
