### ISSUE TITLE
Purging classes using Webpacker in production

### ISSUE THREAD

**Issue by connordoner** [rails/tailwindcss-rails#59]
I'm not sure if I'm overlooking something very simple here, so please forgive me if that's the case, but I can't seem to work out how to purge classes during deployment to production using Webpacker. Would anybody please be so kind as to point me in the right direction? Thank you. :smile:

**Comment by iraszl** [comment]
I'm not sure if this is the ideal solution, but this worked for me. I added this to tailwind.config.css:
`purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: ['./app/views/**/*.*', './app/helpers/**/*.*'],
  },`

**Comment by jefflyne** [comment]
I also need a Webpacker solution since I don't have Sprockets installed. I'm trying to create an app with a react front end and I'm following the tutorial for shakacode/react_on_rails. Please advise if anyone knows a workaround.

**Comment by CHOISEUNGYOUN** [comment]
I also wonder whether it's possible to add another path for purging since I've been using templates with [Viewcomponent](https://viewcomponent.org/)

**Comment by dhh** [comment]
We've dropped webpack support from this gem. It's now exclusively intended for use with sprockets. Will introduce another, easy way to add TW to a webpack setup. But doesn't make sense to share it in the same gem.

**Comment by connordoner** [comment]
Sorry to reopen this, DHH, but is there anything more that you can share about your plans, please? It's going to soon block our progress @Gurste, so if there's anything that we can do to contribute, we're happy to help. :smile:

**Comment by dixpac** [comment]
Since I've removed the webpacker support and we still use webpacker inside our company, I feel somewhat responsible to create webpacker port of this gem 😄 

https://github.com/WizardComputer/tailwindcss-rails-webpacker

Anyone who is interested in contributing you are welcome :)
