### ISSUE TITLE
Ability to tweak Tailwind with its config file using PostCSS

### ISSUE THREAD

**Issue by nickjj** [rails/tailwindcss-rails#6]
In this repo's readme there's:

> If you need to customize Tailwind, you will need to install it the traditional way using Webpacker instead

I see at the moment there's a hardcoded `tailwind.css` file in `app/assets/stylesheets` but in practice it's very common to want to customize Tailwind's fonts, color schemes, etc.. Especially so with Tailwind 2.0 because a lot of the color variants aren't enabled by default and you enable them by customizing the config.

I'm not sure how Tailwind works exactly under the hood but I think Tailwind is just a PostCSS plugin.  The creator of Tailwind walks through creating a build step using PostCSS directly in this video https://egghead.io/lessons/tailwind-set-up-tailwind-and-postcss at the 4:04 to 4:49 mark. Basically after you modify your Tailwind config you would run that build step to generate a new `tailwind.css` file.

Do you foresee an an ability to allow users of this gem to customize Tailwind in the future by having this gem provide a rake task that lets you generate a custom `tailwind.css` file that uses PostCSS under the hood without the need for Webpacker?

I don't know what the limitations are around using PostCSS within the asset pipeline but if it's usable that would also mean you could use PostCSS plugins such as postcss-import, autoprefixer and also let Tailwind handle purging (it does this by default through PostCSS). I would love to be able to drop Webpacker.

**Comment by dhh** [comment]
The main point of this gem is to provide Tailwind CSS for the asset pipeline. Which means having it work on systems that don't even have npm installed. Now, I'd like to see that this essentially can work as a generator for an install under Webpack as well. And that would be the path for customization.

I also know that there are efforts underway to create a customized Tailwind export through a web generator, and I'd love to integrate with that. But I don't see this gem shipping with postCSS or any of that configuration setup internally.
