### ISSUE TITLE
After install can't build imported module

### ISSUE THREAD

**Issue by mkrajewski90** [rails/tailwindcss-rails#60]
Hey,

I have two problems.

1. When run ./bin/rails tailwindcss:install I have 

`Thor::Error: The file /Users/XXX/XXX/XXX/postcss.config.js does not appear to exist
`

I fixed this by adding manually postcss.config.js file in the root document with:
```
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  }
}

```
I'm not sure if that's correct approach and not destroy the build.

2. When refresh a page I receive all the time:

```
macroelements_type_controller.js:4 Uncaught Error: Module build failed: ModuleBuildError: Module build failed: 
@import "tailwindcss/base";
^
      File to import not found or unreadable: tailwindcss/base.
      in /Users/XXX/XXX/XXX/app/javascript/stylesheets/application.scss (line 1, column 1)

```

I can't find the reason of this bug. Any ideas how to fix this?

PS: macroelements_type_controller.js is a stimulus class and there is no connection between tailwind and this controller.

**Comment by dhh** [comment]
We've dropped webpack support from this gem. It's now exclusively intended for use with sprockets. Will introduce another, easy way to add TW to a webpack setup. But doesn't make sense to share it in the same gem.
