### ISSUE TITLE
Release number to match the vendored version of Tailwind

### ISSUE THREAD

**Issue by georgedrummond** [rails/tailwindcss-rails#61]
I’d like to make a proposal that going forward the gem version matches the release of Tailwind vendored in the assets directory. 

Doing so would make it far easier for users to determine what version of Tailwind they are using in the gem, and make bundle updates a breeze.

The gem is currently on version 0.3.3 and that vendors 2.0.2 of Tailwind. 

Could we release 2.2.4 using this convention?

  Huge fan Tailwind, thank you for all your work in making it so easy to use with the asset pipeline 😄

**Comment by dhh** [comment]
I don't think we can make that work, since it would make it impossible to do new releases outside of TW releases. Which we may well need in order to fix bugs or add features.

But I do like the idea of being very clear, perhaps in the README, about which TW is included.
