### ISSUE TITLE
Assets are never re-compiled

### ISSUE THREAD

**Issue by sudhirj** [rails/tailwindcss-rails#7]
There seems to be a caching issue happening—`assets:precompile` does nothing even if new classes are used and purging needs to happen again. I have to run `assets:clobber` first to force a full re-compile.

**Comment by sudhirj** [comment]
Just so I understand, based on https://github.com/rails/tailwindcss-rails/blob/main/lib/tailwindcss/engine.rb

The tailwind file is registered, but that file is never going to change, right? I assume Sprockets will never trigger a new compile if the source files don't change... is there a way to tell Sprockets that the compressor is going to produce different output this time, so it should re-compile even if the inputs are the same?

**Comment by dhh** [comment]
Yeah, we should document this limitation at the moment. Feel free to look into whether there's a way to tell sprockets that the compressor thinks its time for a rebundle, even if the source didn't change.

**Comment by sudhirj** [comment]
Sprockets has a [`depend_on`](https://github.com/rails/sprockets#depend_on) directive that would work, if we pass in the full list of all the files that have been considered for class lookups. Will try to raise a PR using this method, unless someone has a better way to handle this.

**Comment by dhh** [comment]
Oh, that's a great idea. Let's give that a try 👍

**Comment by sudhirj** [comment]
PR #12 raised, uses the `dependencies` key in the output and passes the digest URI for all the files that we extract classnames from.

**Comment by dhh** [comment]
Documented need for clobber in a2abc429a241d44be713d775448b246bf0cec534.

**Comment by sudhirj** [comment]
The way I'm working around this now is to disable the asset cache using the instructions in https://guides.rubyonrails.org/v6.1/asset_pipeline.html#assets-cache-store

I'd suggest documenting this as the recommended approach, it's the only way I can see that handles all the edge cases. 

It also works to automatically fix the Heroku build even if it was deployed without switching off the cache.

**Comment by dhh** [comment]
Made this the default in 2097fc4af21a6ddfc62e73afa391398e498ab7be.
