### ISSUE TITLE
Provide better defaults for the bundled Tailwind CSS

### ISSUE THREAD

**Issue by nileshtrivedi** [rails/tailwindcss-rails#8]
Tailwind UI documentation [mentions](https://tailwindui.com/documentation#getting-set-up) some first-party plugins:

- [x] Include `@tailwindcss/forms` plugin (this provides a basic reset for form styles that makes form elements easy to override with utilities)
- [x] Include `@tailwindcss/typography` plugin (this gives utility classes like `prose`)
- [x] Include `@tailwindcss/aspect-ratio` plugin (this provides a composable API for giving elements a fixed aspect ratio)
- [x] Include [Inter font](https://tailwindui.com/documentation#optional-add-the-inter-font-family)

These change will make the default build a lot more useful.

**Comment by dhh** [comment]
Haven't looked into those, but as long as the plugins work with purging, I'm happy to see them in the default.

**Comment by dhh** [comment]
All done on main now.
