### ISSUE TITLE
rails 7 scaffold system tests fail with -css tailwind

### ISSUE THREAD

**Issue by rubys** [rails/tailwindcss-rails#91]
Reproduction instructions:

```
rm -rf foo
git clone git://github.com/rails/rails.git
./rails/railties/exe/rails new foo --css tailwind --edge
cd foo
rails generate scaffold book title
rails db:migrate
rails test:system
```

Expected results: tests pass

Actual results:

```
Error:
BooksTest#test_should_destroy_Book:
Capybara::ElementNotFound: Unable to find link or button "Destroy this book"
    test/system/books_test.rb:37:in `block in <class:BooksTest>'


rails test test/system/books_test.rb:35

...

Finished in 6.037822s, 0.6625 runs/s, 0.4969 assertions/s.
4 runs, 3 assertions, 0 failures, 1 errors, 0 skips
```

---

In tailwind, the show template uses the word Delete:

https://github.com/rails/tailwindcss-rails/blob/6e6ea6799aa97f0b95cde69a4ca346b7a2eb652d/lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt#L11

In rails main, the show template use the word Destroy:

https://github.com/rails/rails/blob/2b6182cbd68231ed2a26417e3184c3d8ed21c57a/railties/lib/rails/generators/erb/scaffold/templates/show.html.erb.tt#L9

Also in rails main, the system test template uses the word Destroy:

https://github.com/rails/rails/blob/2b6182cbd68231ed2a26417e3184c3d8ed21c57a/railties/lib/rails/generators/test_unit/scaffold/templates/system_test.rb.tt#L48-L53

Either tailwindcss-rails needs to replace the system test template, or it needs to be consistent with the one provided by rails.

**Comment by dhh** [comment]
Changed to use the Rails style: https://github.com/rails/tailwindcss-rails/commit/b6b274851486b806c9628dd28579d123bac2bce6#diff-3df8ef2d1f43b0e5b55ddcc1d2fc3ad12b15fb601b45d5be1bfd7e34e9569187
