### ISSUE TITLE
Rails 7: drop data: confirm from show template

### ISSUE THREAD

**Issue by rubys** [rails/tailwindcss-rails#93]
When generating for rails 7, drop

```
data: { confirm: "Are you sure you want to delete this <%= singular_table_name %>?" }
```

from https://github.com/rails/tailwindcss-rails/blob/b6b274851486b806c9628dd28579d123bac2bce6/lib/generators/tailwindcss/scaffold/templates/show.html.erb.tt#L11

**Comment by dhh** [comment]
Closed via 196825ff41633a538a659e89d73cbeb007cc461e 👍
