### ISSUE TITLE
Upgrade to Tailwind CSS v3

### ISSUE THREAD

**Issue by hudon** [rails/tailwindcss-rails#94]
[Tailwind CSS v3.0 is out](https://tailwindcss.com/blog/tailwindcss-v3), so this issue can track the work (if any) needed for this gem to upgrade to it.

Their upgrade guide is [here](https://tailwindcss.com/docs/upgrade-guide).

**Comment by dixpac** [comment]
Currently this is not possible.

Tailwind 3 removed classic mode, JIT is the only mode for Tailwind 3.
This means that if we build `tailwind.css` with the `npx tailwind build > ./app/assets/stylesheets/tailwind.css"` we will get almost nothing (13KB file size) that just resets browser default styles.

**Comment by dixpac** [comment]
Currently this is not possible.

Tailwind 3 removed classic mode, JIT is the only mode for Tailwind 3.  This means that if we build tailwind.css with the npx tailwind build > ./app/assets/stylesheets/tailwind.css" we will get almost nothing, 13KB file size that just resets browser default styles.

**Comment by dhh** [comment]
Note the incompatibility with 3.0 in the README.

**Comment by hudon** [comment]
This gem now supports Tailwind 3 in v2 and above thanks to this PR: https://github.com/rails/tailwindcss-rails/pull/96
