### ISSUE TITLE
Generator of main closing tag is broken if yield has arguments

### ISSUE THREAD

**Issue by martinadamek** [rails/tailwindcss-rails#98]
It happens for example in JumpstartRails templates, where one of yields uses is `<%= yield :title %>`.
Closing `</main>` tag is not inserted in application.html.erb and the file ends up broken after `./bin/rails tailwindcss:install` is executed.

**Comment by dhh** [comment]
cc @dixpac

**Comment by dixpac** [comment]
Thanks @dhh, I'll take a look tomorrow.
